### ISSUE TITLE
Error using --stdout in a win32 box - CR + LF instead LF

### ISSUE THREAD

**Issue by odicha** [dagwieers/unoconv#112]
-example from console: "python unoconv -f pdf --stdout myfile.odt >> result.pdf
result.pdf is unusable because of bad end of line (in windows text style).
It works fine forcing "binary output" before write to stdout on win32 platforms
Tested & working ok with this ugly patch on def writeBytes( self, seq ):

    def writeBytes( self, seq ):
    +    if sys.platform == "win32":
    +        import os, msvcrt
    +        msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)
        sys.stdout.write( seq.value )

same as http://stackoverflow.com/questions/2374427/python-2-x-write-binary-output-to-stdout

**Comment by dagwieers** [comment]
Merged. Thanks !
