### ISSUE TITLE
Speed wiki

### ISSUE THREAD

**Issue by teu** [dagwieers/unoconv#118]
Hi,

first of all, great work on the tool, loving it!

I'm however having some problems fine tuning my system to work at peak efficiency. I am starting a listener like described "unoconv --listener &" and performing several conversions. What I observed however is that there seams to be only one LibreOffice instance running at a  time and could not find a way of making it use all available resources (presumably running in n+1 threads). Is is possible to run several listeners with several office instances and load balance between them?

Any thoughts on how one can achieve that?

thanks,
teu

**Comment by dagwieers** [comment]
Apparently this is not possible if I have to believe #209.
Maybe bring this up on the LibreOffice forums ?
