### ISSUE TITLE
UnoException when converting xlsx to html (ErrCode 3088)

### ISSUE THREAD

**Issue by mohabusama** [dagwieers/unoconv#119]
Cannot convert xlsx to html

$ unoconv -f html /tmp/Book1.xlsx
unoconv: UnoException during export phase:
Unable to store document to file:///tmp/Book1.html (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"HTML (StarWriter)" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x19e9918{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

$ unoconv --version
unoconv 0.6
...
[GCC 4.6.3]
LibreOffice 3.5

Converting to pdf or xls worked fine. It appears the problem exists only with the HTML format conversion.

**Comment by dagwieers** [comment]
Just as a reference, ErrCode 3088 means:

Binary: 000:01100:00010000

    Area: 0 (ERRCODE_AREA_TOOLS)
    Class: 12 (ERRCODE_CLASS_WRITE)
    Code: 16 (ERRCODE_IO_CANTWRITE)

So that seems to indicate a permission/ACL/SELinux issue ?

**Comment by dagwieers** [comment]
I am closing this issue. If this is still pertinent to you, feel free to reopen the issue, check all the bullets from the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) and provide us with the details and a reproducer.

Thanks for the feedback !

**Comment by mohabusama** [comment]
Hi @dagwieers 

Thanks for the follow up.

I have done some tests and all seems to be working fine. May be indeed it was an environment problem.

For ref:

```
$ unoconv --version
unoconv 0.6
...
[GCC 4.8.2]
LibreOffice 4.2
```

Thanks!

**Comment by dagwieers** [comment]
Thanks for getting back to us ! It always helps to get closure ;-)
