### ISSUE TITLE
Installing / running unoconv on Mac Os X

### ISSUE THREAD

**Issue by schwarzf** [dagwieers/unoconv#125]
I installed LibreOffice with the current installer 'LibreOffice_4.0.2_MacOS_x86.dmg' and run the latest version (GitHub master branch) of unoconv:

./unoconv 
dyld: Library not loaded: /usr/local/libodep/lib/libintl.8.dylib
  Referenced from: /Applications/LibreOffice.app/Contents/MacOS/LibreOfficePython.framework/Versions/3.3/Resources/Python.app/Contents/MacOS/LibreOfficePython
  Reason: image not found
Trace/BPT trap: 5

The /usr/local/libodep/lib/libintl.8.dylib library does not exist at my system. Have you any suggestions what I have forgotten?

**Comment by dagwieers** [comment]
With all the heads up I am going to close this issue. If you still have a related problem, feel free to reopen this issue.
