### ISSUE TITLE
Failure to convert when specifying a non-existing output directory

### ISSUE THREAD

**Issue by gazofnaz** [dagwieers/unoconv#133]
Hi Guys,

I noticed from 0.5 onwards there was a change in the way **--output** & **--outputpath** are used. It's entirely possible that the problem below is just me misunderstanding the available options :)

In the application I support, we specify a custom output directory for the exported document. This directory does not exist at the point of execution. It is created on the fly.

This process works with v0.4, but fails in 0.5 & 0.6.

In 0.5 the conversion starts, but LibreOffice dies when writing the export to disk, and leaves behind the ominous .lock file.

I've noticed I can fix the problem by altering unoconv:

In version 0.5, line 824, change

    outputfn = op.output

to 

    outputfn = os.path.join(op.output, os.path.basename(outputfn) + os.extsep + outputfmt.extension)

This seems to mimic the behavior of 0.4... but my python is not so great!

For reference here is the command I'm running:

    unoconv -f 'docx' -v -d 'web' -o '/home/me/somefilename/' --timeout '60' '/home/me/somefilename.html'

And the software:

    unoconv 0.5
    Written by Dag Wieers <dag@wieers.com>
    Homepage at http://dag.wieers.com/home-made/unoconv/

    platform posix/linux2
    python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
    [GCC 4.4.5]
    LibreOffice 3.5

And the output:

    Verbosity set to level 3
    Connection type: socket,host=localhost,port=2002;urp;StarOffice.ComponentContext
    Office base location: /usr/lib/libreoffice
    Office binary location: /usr/lib/libreoffice/program
    Existing listener not found.
    Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
    LibreOffice listener successfully started. (pid=26063)
    Input file: /home/me/somefilename/somefilename.html
    Selected output format: Microsoft Office Open XML [.docx]
    Selected office filter: MS Word 2007 XML
    Used doctype: web
    Output file: /home/me/somefilename/somefilename/
    unoconv: UnoException during export phase: Unable to store document to file:///home/me/somefilename/     with properties ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"MS Word 2007     XML" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (    long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x34c8b88{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.    XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterData",     Handle = (long)0x0, Value = (any){ ([]any){} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){     Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }).     Exception:
    Terminating LibreOffice instance.
    LibreOffice instance unsuccessfully closed, sending TERM signal.
    Waiting for LibreOffice instance to exit.

**edit, included the wrong output message

**Comment by dagwieers** [comment]
This should be fixed now. Feel free to reopen this issue if you still experience unexpected behavior.
Sorry for the inconvenience :-/
