### ISSUE TITLE
Issue with .TXT input extension (ErrCode 3088)

### ISSUE THREAD

**Issue by kingdonb** [dagwieers/unoconv#136]
There is apparently something wrong with this file, but it seems to be the only problem is the extension of TXT.

Is there a way to force this to be interpreted as CSV input?  (Change the extension to .csv, duh, but I would have thought there would be an input flag.  The same bad behavior with or without `-d spreadsheet`.  When I open the file in LibreOffice in a spreadsheet window, the right thing happens even with .TXT extension.)

```
$ ~/unoconv-0.6/unoconv -d spreadsheet -i FilterOptions=44,34,76,2,2/2/2/2/2/2/2/2/2/2/2/2/2 -o test3.csv -f csv BADFILE.TXT 
unoconv: UnoException during export phase:
Unable to store document to file:///home/kbarrett/redacted/test3.csv (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"Text - txt - csv (StarCalc)" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x14dee08{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterOptions", Handle = (long)0x0, Value = (any){ (string)"44,34,76" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```

**Comment by dagwieers** [comment]
Just as a reference, ErrCode 3088 means:

Binary: 000:01100:00010000
 - Area: 0 (ERRCODE_AREA_TOOLS)
 - Class: 12 (ERRCODE_CLASS_WRITE)
 - Code: 16 (ERRCODE_IO_CANTWRITE)

So that seems to indicate a permission/ACL/SELinux issue ?

**Comment by AngelusWeb** [comment]
I'm still having this problem!

**Comment by AngelusWeb** [comment]
There are no permissions issues. I don't have SElinux enabled. And I'm writing to a folder in my home directory, and running as Root so permissions aren't an issue.

**Comment by dagwieers** [comment]
@AngelusWeb Are you reporting the exact same issue (the ErrCode from LibreOffice is not an indication that the problem/cause is identical). Please open a new issue if you have a different ErrCode 3088 error. Or confirm that you have the exact same issue as reported.

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
