### ISSUE TITLE
Document does not maintain format when converting to PDF

### ISSUE THREAD

**Issue by MirkoCindric** [dagwieers/unoconv#137]
When l convert l docx file that has headings that are bold for example it does not maintain the bold for that heading and also changes the font instead of using what was originally used

**Comment by dagwieers** [comment]
Please read the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) and follow each bullet. I need to know if this is a LibreOffice issue, and if this is still an issue with the latest unoconv from the master branch and a recent Libreoffice.

And if you have more details to reproduce the problem, feel free to reopen this issue.

Thanks for the feedback !
