### ISSUE TITLE
Mapping CSS to OTT styles

### ISSUE THREAD

**Issue by forgandenny** [dagwieers/unoconv#142]
I use unoconv to convert html to pdf and it works great. I only have some issues with trying to match CSS rules and styles in OTT template. For example setting padding and margins on UL and LI elements in css does have any effect in a final PDF file. Is there a  reference of how to combine css with ott to style html elements? Are there any html elements that cannot be modified while converting to PDF?

**Comment by dagwieers** [comment]
if you, or anyone else, has more information on how to tackle this and how unoconv could help in mapping CSS and ODF styles, I would be very interested to hear/learn from you !

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
