### ISSUE TITLE
Gdk-WARNING **: locale not supported by C library

### ISSUE THREAD

**Issue by andresrivas1506** [dagwieers/unoconv#147]
Hello, when I try unoconv --listener & appears this:
root@B252 [~]# unoconv --listener &
[1] 6656
root@B252 [~]# 
(process:6658): Gdk-WARNING **: locale not supported by C library

(soffice:6658): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/lib64/libreoffice/program/soffice.bin X11 error: Can't open display: 
   Set DISPLAY environment variable, use -display option
   or check permissions of your X-Server
   (See "man X" resp. "man xhost" for details)

[1]+  Done                    unoconv --listener
root@B252 [~]# 
/* ========== */
---------> And I try:
root@B252 [~]# unoconv -f png file.ppt 

(process:6724): Gdk-WARNING **: locale not supported by C library

(soffice:6724): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/lib64/libreoffice/program/soffice.bin X11 error: Can't open display: 
   Set DISPLAY environment variable, use -display option
   or check permissions of your X-Server
   (See "man X" resp. "man xhost" for details)
Error: Unable to connect or start own listener. Aborting.
root@B252 [~]# 
Please help me, i use Centos 6.3

**Comment by dagwieers** [comment]
I am closing this ticket because we did not get any feedback.
The documentation provides ample guidance for related issues.
If this issue is still pertinent, feel free to reopen this issue.
