### ISSUE TITLE
unoconv and png (ErrCode 2074)

### ISSUE THREAD

**Issue by satels** [dagwieers/unoconv#149]
file: http://yadi.sk/d/RFzb1GWe6sEAI

unoconv -f png --stdout regionyi-dostavkidocx.pdf

unoconv: UnoException during export phase:
Unable to store document to private:stream (ErrCode 2074)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"draw_png_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0xa0c9f8c{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

**Comment by dagwieers** [comment]
Just as a reference, ErrCode 2074 means:

Binary: 000:01000:00011010
 - Area: 0 (ERRCODE_AREA_TOOLS)
 - Class: 8 (ERRCODE_CLASS_PARAMETER)
 - Code: 26 (ERRCODE_IO_INVALIDPARAMETER)

It seems to indicate we are using the UNO API incorrectly, somehow...

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
