### ISSUE TITLE
CSV export - FilterOptions ignored

### ISSUE THREAD

**Issue by Paradiesstaub** [dagwieers/unoconv#161]
Ubuntu 13.04
unoconv 0.5
LibreOffice 4.0.2.2

When exporting a .ods file to .csv the FilterOptions get ignored, it's not possible (for me) to set another field separator (semicolon) as specified [here](http://wiki.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Filter_Options). The output contains always commas as field separators.

Update:
[LibreOffice Delimiter bug #68786](https://www.libreoffice.org/bugzilla/show_bug.cgi?id=68786)

    unoconv -e FilterOptions="59,34,0,1,9" --format=csv test.ods

**Comment by dagwieers** [comment]
Works fine for me too. So I am closing this issue.
If you still have this problem with the master branch and a recent LibreOffice, please reopen this ticket.

Thanks for the feedback !

**Comment by Shadok** [comment]
Same issue here with Ubuntu 16.04 :
# unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
LibreOffice 5.1.4.2

/usr/bin/unoconv -f csv -e FilterOptions=44,34,76 file.ods
