### ISSUE TITLE
How to Install unoconv install mac Os-x 10.8.4 ? 

### ISSUE THREAD

**Issue by rajeevkannav** [dagwieers/unoconv#162]
How to Install unoconv install mac Os-x 10.8.4 ?

**Comment by dagwieers** [comment]
I don't know a lot of MacOS X, but you can apparently install it from [Homebrew](http://brew.sh/).
Use `brew install unoconv --HEAD` until the new version is released.

**Comment by EvgeniyGorbachev** [comment]
A good instruction for installation: https://docs.moodle.org/35/en/Universal_Office_Converter_(unoconv)#Installing_unoconv_on_OS_X
