### ISSUE TITLE
HTML 2 docx: images and table borders problem

### ISSUE THREAD

**Issue by lyudmila-petrova** [dagwieers/unoconv#173]
Hi! I have a problem with html 2 docx conversion.
1. Unoconv with LibreOffice 3.5 embeds images into docx file if src is a full system path, but no table borders.

Sample html:

<pre>
&lt;table border='1'&gt;...

&lt;img src='/var/www/full/path/to/image.png' ... /&gt;
</pre>

1. Unoconv with LibreOffice 4 do not embed images with full system path, but table borders work fine.

Is there a way to embed images and process table borders at the same time?

**Comment by dagwieers** [comment]
Can you please try the latest unoconv from the master branch together with the latest LibreOffice ?

Thanks in advance !

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
