### ISSUE TITLE
Error 2074 when converting filenames with non-ascii characters

### ISSUE THREAD

**Issue by NDakotaBE** [dagwieers/unoconv#18]
As I am trying to export doc files to jpeg I get the following error. 

I have restarted all my instances of openoffice, reinstalled everything, but still the same issue. 
Any idea what the reason is as I am on a dead end

```
Input file: EWAD-CZ_press_release.doc
Selected output format: Joint Photographic Experts Group [.jpg]
Selected ooffice filter: draw_jpg_Export
Used doctype: graphics
unoconv: UnoException during conversion in <class __main__.com.sun.star.task.ErrorCodeIOException at 0x7f1e302f0590>:
ERROR: The provided document cannot be converted to the desired format. (code: 2074)
```

**Comment by dagwieers** [comment]
I can no longer reproduce this with recent LibreOffice versions. So I assume this is fixed upstream.

Can you please try again with the latest unoconv version from the master branch and a recent LibreOffice ? If you still have a problem, feel free to reopen this issue.
