### ISSUE TITLE
UTF8 encoded text to html leaves UTF8 BOM characters in the HTML result

### ISSUE THREAD

**Issue by bkmohandas** [dagwieers/unoconv#181]
UTF8 encoded text file to html leaves UTF8 BOM characters in the HTML result

unoconv --format html --export FilterOptions=UTF8 --output file.html file.txt
unoconv --format html --export FilterOptions=76 --output file.html file.txt

If the text contents are : 

Example Text file 

then the html result is: 

ï»¿ Example Text file 

Am I missing something here?
Thanks,

PS:
libreoffice does not exhibit this problem. The following command 

soffice --headless --convert-to htm:HTML file.txt

works. The html result does not display the UTF8 BOM characters.

**Comment by dagwieers** [comment]
I would like to understand what you are saying, but I don't at this time.

If you could provide me with an exact set of commands to reproduce this (like I did above), I am willing to look at this again. But I tried everything again and it works perfectly fine on my system. I wish I could help here.

Feel free to reopen this issue with more detailed information.

**Comment by dagwieers** [comment]
Alright, forgive me my ignorance. My input file was indeed not with a BOM character.

I now found that the BOM sequence is this: "0xEF 0xBB 0xBF" (so no 0xFF). And started all over:

```bash
[dag@moria unoconv]$ file tests/test.txt
tests/test.txt: UTF-8 Unicode (with BOM) English text, with very long lines, with overstriking
[dag@moria unoconv]$ hexdump -C tests/test.txt | grep 'ef bb bf' 
00000000  ef bb bf 20 20 20 20 0a  0a 44 69 73 61 73 74 65  |...    ..Disaste|
[dag@moria unoconv]$ /opt/libreoffice5.0/program/python unoconv --format html --export FilterOptions=UTF8 tests/test.txt
[dag@moria unoconv]$ hexdump -C tests/test.html | grep 'ef bb bf' 
[dag@moria unoconv]$
```

So now the input file does have a BOM sequence at the very start, but my HTML output does not seem to get it. This is of course with LibreOffice 5.0, so I also tried using LibreOffice 4.0 (the one that was current around the time you reported this):

```bash
[dag@moria unoconv]$ file tests/test.txt
tests/test.txt: UTF-8 Unicode (with BOM) English text, with very long lines, with overstriking
[dag@moria unoconv]$ hexdump -C tests/test.txt | grep 'ef bb bf' 
00000000  ef bb bf 20 20 20 20 0a  0a 44 69 73 61 73 74 65  |...    ..Disaste|
[dag@moria unoconv]$ /opt/libreoffice4.0/program/python unoconv --format html --export FilterOptions=UTF8 tests/test.txt
[dag@moria unoconv]$ hexdump -C tests/test.html | grep 'ef bb bf' 
[dag@moria unoconv]$
```
Same thing. Can you verify you still have this issue with the unoconv version from the master branch and a recent LibreOffice ?

Thanks in advance !

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
