### ISSUE TITLE
Combines with asciidoc and docbook2odf/xhtml2odt to create PDF or Word (.doc) files 

### ISSUE THREAD

**Issue by roozgar** [dagwieers/unoconv#188]
in Features list here 
http://dag.wiee.rs/home-made/unoconv/#features
there is a way to create doc file

is any one worked with this?
i cant find any document regarding this tools

thank you

**Comment by dagwieers** [comment]
What I do is:

    AsciiDoc --> FODT --> DOC

Using the following tools:

 - asciidoc  --  http://asciidoc.org/
 - asciidoc-odf  --  https://github.com/dagwieers/asciidoc-odf
 - LibreOffice  --  http://www.libreoffice.org/
 - unoconv  --  https://github.com/dagwieers/unoconv

Using this:

    asciidoc -b odt mydocument.asciidoc
    unoconv -f doc -o mydocument.doc mydocument.fodt
    unoconv -f pdf -o mydocument.pdf mydocument.fodt
