### ISSUE TITLE
Unoconv gets stuck converting one HTML into PDF

### ISSUE THREAD

**Issue by mauricioblur** [dagwieers/unoconv#191]
I'm trying to convert one HTML file into one PDF file. Usually, the process works fine with an important part of the HTML files. The command looks like:

*unoconv -f pdf -vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv search_003.html*

The output is:
```
Verbosity set to level 49
Connection type: socket,host=localhost,port=2002;urp;StarOffice.ComponentContext
Office base location: /usr/lib/libreoffice
Office binary location: /usr/lib/libreoffice/program
Existing listener not found.
Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=30901)
Input file: search_003.html
Selected output format: Portable Document Format [.pdf]
Selected office filter: writer_pdf_Export
Used doctype: document
Output file: search_003.pdf
Terminating LibreOffice instance.
Waiting for LibreOffice instance to exit.
```
But for a few files, the process gets stuck on "Input file":
```
Verbosity set to level 49
Connection type: socket,host=localhost,port=2002;urp;StarOffice.ComponentContext
Office base location: /usr/lib/libreoffice
Office binary location: /usr/lib/libreoffice/program
Existing listener not found.
Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=30978)
Input file: tvrnews.tvr.ro.html
```
 
If I press CTRL + C, then:
```
Verbosity set to level 49
Connection type: socket,host=localhost,port=2002;urp;StarOffice.ComponentContext
Office base location: /usr/lib/libreoffice
Office binary location: /usr/lib/libreoffice/program
Existing listener not found.
Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=30978)
Input file: tvrnews.tvr.ro.html
^Cunoconv: SystemError during update-indexes phase: Couldn't instantiate python representation of structered UNO type com.sun.star.lang.DisposedException
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1053, in <module>
    die(exitcode)
  File "/usr/bin/unoconv", line 919, in die
    if convertor.desktop.getCurrentFrame():
```
My unoconv version is:
```
unoconv 0.5
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux2
python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3]
LibreOffice 4.0

build revision $Rev$
```

Any idea or suggestion of how to manage this problem?

Thank you very much!

**Comment by dagwieers** [comment]
It may be useful to test this document again with a recent LibreOffice and in case it still has difficulties, report this to the LibreOffice project. They may be able to improve their support for *broken* documents.

 I will close this issue. Thanks again for the feedback !

**Comment by charlescurley** [comment]
I seem to have hit this issue. In my case, I did open the offending document and convert to text manually.

The error message I get, after hitting control C, is:

unoconv: SystemError during import phase:
Couldn't instantiate python representation of structured UNO type com.sun.star.lang.DisposedException
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1278, in <module>
    die(exitcode)
  File "/usr/bin/unoconv", line 1131, in die
    if convertor.desktop.getCurrentFrame():
uno.DisposedException: Binary URP bridge already disposed

No output file is created.

This is on Debian 8.9, jessie. Libreoffice version is 1:5.2.7-1~bpo8+1, and unoconv is 0.7-1.1~bpo8+1. The offending document is http://legisweb.state.wy.us/statutes/compress/title35.docx. It is one of several (http://legisweb.state.wy.us/LSOWEB/StatutesDownload.aspx); the rest all converted successfully using unoconv.
