### ISSUE TITLE
Issue with date formats

### ISSUE THREAD

**Issue by denisgeorge** [dagwieers/unoconv#194]
Hello Dag,

I have a program that converts writer or calc files to pdf. 

It actually generates dynamically the files content.xml and styles.xml, zips everything in an ods or odt file (with the other necessary files) before asking unoconv to do the conversion.

It works well on an ubuntu 12.04 with LibreOffice 3.5, unoconv 0.4, python 2.7.3, tomcat6 and java6 (the printings are generated by a java app).

On the other hand, on an ubuntu 12.10 with LibreOffice 3.6, unoconv 0.5, python 2.7.3, tomcat6 and java6, the date format is in the wrong locale : MM/DD/YY instead of DD/MM/YYYY.

Do you have any hints to explain the differences between the results obtained ?

Both server have a french locale fr_FR.UTF-8 installed. 
The french language package for libreoffice has also been installed on both servers.

Thanks,

Denis

**Comment by dagwieers** [comment]
Indeed, I would expect LibreOffice to have the exact same problem. You can try `soffice --convert-to` in order to verify.

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
