### ISSUE TITLE
Facing problem during conversion

### ISSUE THREAD

**Issue by jasvirsingh10** [dagwieers/unoconv#196]
Hi,

I am facing problem while conversion 
'UNO IllegalArgument during import phase: Source file cannot be read. URL seems to be an unsupported one.'

Please tell me how i remove it. i am unable to solved it.

Some details :
--------------------------------------------------------------------------------------
[root@v01 /usr/bin]$ unoconv --version
unoconv 0.5
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux2
python 2.4.3 (#1, Jan  9 2013, 06:47:03)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]
OpenOffice.org 3.1

build revision $Rev$
[root@v01 /usr/bin]$
-----------------------------------------------------------------------------
Command used for conversion : unoconv Jasper_Adolfs_Edam.docx 
-----------------------------------------------------------------------------
Server OS Details :+1: 
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 5.10 (Final)
Release:        5.10
Codename:       Final

Linux 2.6.18-371.6.1.el5 x86_64

Linux version 2.6.18-371.6.1.el5 (mockbuild@builder10.centos.org) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)) #1 SMP Wed Mar 12 20:03:51 EDT 2014
----------------------------------------------------------------------
OpenOffice.org 3.1  310m19(Build:9420)

--------------------------Getting this error message also--------------------------------
/usr/lib64/openoffice.org3/program/soffice
/usr/lib64/openoffice.org3/program/soffice.bin X11 error: Can't open display:
   Set DISPLAY environment variable, use -display option
   or check permissions of your X-Server
   (See "man X" resp. "man xhost" for details)

**Comment by dagwieers** [comment]
If this is still an issue with the latest release or the master branch, please reopen this issue.
