### ISSUE TITLE
Using unoconv with pyenv

### ISSUE THREAD

**Issue by zemlya25** [dagwieers/unoconv#204]
Can't use unoconv with installed isolated python with pyenv. 
With system installed PY (Ubuntu 12.04) it works fine. Tryed to make symlink to uno.py and unohelper.py libs, but it crashed while trying to load .so libs

crash message
http://pastebin.com/uzucTXSU

**Comment by dagwieers** [comment]
I don't know pyenv, can you elaborate and/or provide a pull request so I can understand what the purpose is ?

Thanks in advance !

**Comment by zemlya25** [comment]
Problem solved.
We don't use pyenv anymore.

We were used unoconv with env with python3 as default installed python version. Unoconv were started in isolated python installation (with pythonbrew or smth else).
Later everything were reconfigured for different accout for every task.
Now unoconv works fine.

**Comment by dagwieers** [comment]
Thanks for the feedback. I will close this ticket accordingly.
