### ISSUE TITLE
libre office 4.3 requires double-dash args (--headless instead of -headless)

### ISSUE THREAD

**Issue by jimav** [dagwieers/unoconv#205]
Options -headless -invisible etc. are passed when starting a local open/libre office instance.   However for several years these options "officially" take double dashes per the GNU option convention (e.g. --headless) [at least since LO 3.6].

The upcoming Libre Office 4.3 now emits deprecation warnings when the old single-dash forms are used, so it would be great if unoconv was changed to generate the double-dash style.

$ UNO_PATH=/path/to/libreofficedev4.3-alpha1 unoconv -o output.pdf -f pdf input.odt
Warning: -headless is deprecated.  Use --headless instead.
Warning: -invisible is deprecated.  Use --invisible instead.
Warning: -nodefault is deprecated.  Use --nodefault instead.
Warning: -nofirststartwizard is deprecated.  Use --nofirststartwizard instead.
Warning: -nologo is deprecated.  Use --nologo instead.
Warning: -norestore is deprecated.  Use --norestore instead.
Warning: -accept=socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext is deprecated.  Use --accept=socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext instead.

**Comment by dagwieers** [comment]
This should be fixed. If you still have an issue with a recent version, please reopen this issue and provide us more information. Thanks !
