### ISSUE TITLE
No response under php by exec.

### ISSUE THREAD

**Issue by forpizinmind** [dagwieers/unoconv#206]
Hi,
My server is CentOS 6.5 + Apache. I want to use php to transfer ppt to pdf on the fly. An script like "/usr/bin/unoconv -f pdf helloworld.ppt" works fine under command line as user=>webuser. But the same script failed by "exec" in the php.

First,I had checked the user by exec(whoami) in the php, and it is  just as the same (webuser) as the command line environment.

So, I tried to see whether the unoconv work in php by exec('unoconv -h',$output, $return_var).The return_var was 1,and output was an empty array.~~"

I had also tried wrap the script in an shell file,but also works under command line failed in the php. Could someone give me an hint?Thanks.

**Comment by dagwieers** [comment]
We are tracking this problem (and the future fix) through #87.
As a result I am closing all other related open issues.
