### ISSUE TITLE
Missing binary location

### ISSUE THREAD

**Issue by phonedog365** [dagwieers/unoconv#207]
LibreOffice 4.2.4002
MacOS 10.9.3

$ unoconv -f csv file.xlsx 
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by dagwieers** [comment]
I am closing this issue. If this issue is still pertinent, and other issues (like #177) are not related to your problem, feel free to open this issue.

Thanks for the feedback !
