### ISSUE TITLE
--output is broken in master

### ISSUE THREAD

**Issue by graaff** [dagwieers/unoconv#210]
As explained in a comment on commit 363a8691a177025ae69341534f78d73e9d8f20f3 that commit breaks the --output option by always creating a directory to place the files in, rather than using the --output option as a file when it does not yet exist.

If this change was intentional then the unoconv.1 man page should be updated accordingly.

**Comment by dagwieers** [comment]
This should be fixed. Can you test if what you expect is what happens ?

Thanks in advance !

**Comment by dagwieers** [comment]
Feel free to reopen this issue if it is not fixed.
