### ISSUE TITLE
centos 6 unoconv doesn't work

### ISSUE THREAD

**Issue by beinbliss** [dagwieers/unoconv#216]
Hello,

yum install libreoffice*
git clone https://github.com/dagwieers/unoconv
make install
unoconv --help
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

rpm -qa|grep libre
libreoffice-writer-4.0.4.2-9.el6.x86_64
libreoffice-headless-4.0.4.2-9.el6.x86_64
libreoffice-opensymbol-fonts-4.0.4.2-9.el6.noarch
libreoffice-ure-4.0.4.2-9.el6.x86_64
libreoffice-core-4.0.4.2-9.el6.x86_64

CentOS release 6.5 (Final)

(by itself libre works and converts through cli)

**Comment by dagwieers** [comment]
Feel free to reopen this issue if you have more information to share, or if this issue is still pertinent.
Thanks !
