### ISSUE TITLE
After starting the system,the fisrt time I use unoconv always fail.

### ISSUE THREAD

**Issue by JiayiFu** [dagwieers/unoconv#219]
My system is CentOS 6.3.
Everytime I use unoconv after startint the system,it always gets error:

[root@localhost data]# ls
doc.doc  doc.txt
[root@localhost data]# unoconv -f pdf doc.doc
Failed to connect to /usr/lib/libreoffice/program/soffice.bin (pid=1400) in 6 seconds.
Connector : couldn't connect to socket (Success)
Error: Unable to connect or start own listener. Aborting.
[root@localhost data]# unoconv -f pdf doc.doc
[root@localhost data]# ls
doc.doc  doc.pdf  doc.txt

But I use unoconv after it once again,success.
I tried many times , it just the first time after starting system would get error and after this time the unoconv can work.
I am very confused and who can give me some advice, I would be very grateful.

**Comment by scragg0x** [comment]
I'm having the same issue.

@JiayiFu did you ever figure this out?

**Comment by dagwieers** [comment]
I have that same issue BTW.
Still need to figure it out, maybe using -vvv helps find the cause ?

**Comment by dagwieers** [comment]
I think we got this fixed this evening thanks to a contribution.

Can you test to see if this issue is still valid for you ?
If so, please reopen this issue !

Thanks !

**Comment by JiayiFu** [comment]
Thanks for your attention and help.
I'm afraid that I can't test it recently because I had changed my OS include all workstation.
If I had time I will test it and present the result.
If it still be a problem I will reopen this issue and tell you.
Thank you again!
@dagwieers

**Comment by akkana** [comment]
Still a problem two years later with unoconv 0.7 on Debian testing (buster/sid). Is there any way to reopen github issues, or should I file this as a new issue?

**Comment by dagwieers** [comment]
I can reopen, but I prefer a new issue as it's not clear if this is the same issue.
