### ISSUE TITLE
--version and --help commands should return 0 status code

### ISSUE THREAD

**Issue by gabceb** [dagwieers/unoconv#222]
if `--version` and `--help` command execute successfully they should return 0 instead of 255. I checked some of the most commonly used command line tools (git, grep, vim, etc) and they all return 0 on `--version` and `--help`.

I ran into this issue when using `unoconv --version` to check if unoconv was installed properly.

I can provide a PR unless someone disagrees with this.

**Comment by dagwieers** [comment]
You are correct, a PR would be appreciated.

**Comment by gabceb** [comment]
Thanks @dagwieers. Sorry that I missed your previous comment

**Comment by dagwieers** [comment]
No problem. I try to engage people to look at the code, especially for trivial matters :-)
I don't know why it wasn't returning 0 from the  very start though...
