### ISSUE TITLE
an error occurred when called by lua in nginx

### ISSUE THREAD

**Issue by ltpao** [dagwieers/unoconv#224]
File "/usr/bin/unoconv", line 1112, in <module>
    office_environ(of)
  File "/usr/bin/unoconv", line 203, in office_environ
    os.environ['PATH'] = realpath(office.basepath, 'program') + os.pathsep + os.environ['PATH']
  File "/opt/libreoffice4.1/program/python-core-3.3.0/lib/os.py", line 669, in __getitem__
    value = self._data[self.encodekey(key)]
KeyError: b'PATH'

-------------------------------------
bug resolved
source:
os.environ['PATH'] = realpath(office.basepath, 'program') + os.pathsep + os.environ['PATH']
replace:
os.environ['PATH'] = realpath(office.basepath, 'program') + os.pathsep + os.environ.get('PATH', '.')

**Comment by dagwieers** [comment]
Maybe relevant also to this case is the following:
https://github.com/dagwieers/unoconv/issues/87#issuecomment-18800070
