### ISSUE TITLE
PDF to doc/xls/html/xhtml fails

### ISSUE THREAD

**Issue by tpynak** [dagwieers/unoconv#226]
Hi,
Using:
Linux roman-desktop 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:31:23 UTC 2014 i686 i686 i686 GNU/Linux
Latest (from github) version of unoconv
LibreOffice 4.2.7.2 420m0(Build:2)
Python 2.7 and 3.4 tried.

I can't convert PDF files to dox/xls/html/xhtml/txt format. However it converts to png for example.
I always get an error:

"roman@roman-desktop:~/test/unoconv$ sudo python3 unoconv -f doc /home/roman/test/24.pdf
unoconv: UnoException during export phase:
Unable to store document to file:///home/roman/test/24.doc (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"MS Word 97" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0xa00b24c{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
roman@roman-desktop:~/test/unoconv$ "

**Comment by shividhar** [comment]
+1 Still doesn't work

**Comment by dagwieers** [comment]
You cannot convert a PDF file to a document-type format, but you can convert a PDF file to a graphics-type format like ODG.

This works on my system with LibreOffice 4.4.3.1:

    unoconv -f odg test.pdf

Please re-open the ticket if this does not seem to work.

**Comment by dagwieers** [comment]
PS Also use the Troubleshooting section on the README to help you debug your issue. I think the problem may be that you are NOT using the LibreOffice supplied python binary.

**Comment by andreshg112** [comment]
I'm having the same issue when trying to convert many files at the same time.
```
unoconv: UnoException during export phase:
Unable to store document to file:///opt/em7/gui/ap/www/em7/libs/od_templates/populated/Asset_List_em7admin_20210428153611.pdf (ErrCode 3088)
Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"calc_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x2635748{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```
