### ISSUE TITLE
backtrace trying to convert *.ods to xls format on Slackware64-14.1

### ISSUE THREAD

**Issue by fishforbreakfast** [dagwieers/unoconv#228]
Hi,

Thank you for the great software.  I was attempting to convert a spreadsheet from ods to xls using unoconv.  I have LibreOffice 4.3.2 from alien repository for slackware installed.  I receive this output when trying to convert to xls:
fred@rumpuscat:~/Documents/PostgreSQL/Lettering-2014_15> unoconv -f xls Lettering-Fall_2014_15_4.3.ods 
unoconv: UnoException during export phase:
Unable to store document to file:///home/fred/Documents/PostgreSQL/Lettering-2014_15/Lettering-Fall_2014_15_4.3.xls (ErrCode 264971)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"MS Excel 97" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x29cdbe8{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

And this when trying to create an xlsx file:

fred@rumpuscat:~/Documents/PostgreSQL/Lettering-2014_15> unoconv -f xlsx Lettering-Fall_2014_15_4.3.ods 
unoconv: UnoException during export phase:
Unable to store document to file:///home/fred/Documents/PostgreSQL/Lettering-2014_15/Lettering-Fall_2014_15_4.3.xlsx (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x2fefc58{, supportedInterfaces={com.sun.star.io.XOutputStream,com.sun.star.lang.XTypeProvider}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"Calc MS Excel 2007 XML" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

I am not sure if it is LibreOffice or something else.

Thank you for any clues.

Cheers,

Fred

**Comment by dagwieers** [comment]
Did you follow some of the advice in the Troubleshooting section on the README ?

Because there are a few things you can do to figure out where exactly the problem lies (LibreOffice, python, system, unoconv, ...). Trying the latest LibreOffice is probably the first thing to try.

**Comment by dagwieers** [comment]
Feel free to reopen this issue if you have more information to share and the issue is still pertinent.
Thanks !
