### ISSUE TITLE
Cant convert a pdf file to a doc file

### ISSUE THREAD

**Issue by Ranjithkaipra** [dagwieers/unoconv#229]
Hi,  

I tried to convert a pdf file to doc file  with the below command it executed successfully. 

unocnov -f doc test.pdf

But when i open the doc file it shows  like this

665 0 obj <</Length 326/C 333/Filter/FlateDecode/I 374/L 317/S 228>>stream 
x�b```b``�d`a``�b#f@#a#V#6�8�B!A%&#f�#�3�է�#�?�8�Ǵ*�##�x��dx��5�5ޖ)P}#�e.�K8�###(�7X��1�Y��j�g�H#7���1��#J�#�f�#y�##Jݭ�>Wf�\	Gg9�'#�#�##4F���Aɥ#�b�h,#R�##��#�͖��#�����#��*�#��Z#i#��`=�

Any idea?

**Comment by dagwieers** [comment]
You cannot convert a PDF file to a document-type format.
What you can do is convert a PDF to a graphics-type format like ODG.

    unoconv -f odg test.pdf

Which you can then open with LibreOffice Draw.

**Comment by dagwieers** [comment]
Closing this issue. Feel free to reopen if you have a related issue.

**Comment by lvsenlin** [comment]
It does't work now
