### ISSUE TITLE
unoconv: Cannot find a suitable office installation on your system.

### ISSUE THREAD

**Issue by kksinf** [dagwieers/unoconv#231]
$ sudo apt-get remove --purge libreoffice*
$ sudo tar zxvf Apache_OpenOffice_4.1.0_Linux_x86_install-deb_en-US.tar.gz
$ cd en-US/DEBS
$ dpkg -i *.deb
$ cd desktop-integration
$ dpkg -i *.deb
$ ls /etc/openoffice4/python*
   python, python.bin

**Comment by dagwieers** [comment]
We thinkg this is a duplicate to #211. Please provide feedback in that thread.
As a result I am closing this issue. Thanks for the feedback !
