### ISSUE TITLE
unoconv: RuntimeException during import phase: Office probably died. Unsupported URL 

### ISSUE THREAD

**Issue by Ranjithkaipra** [dagwieers/unoconv#232]
Hi

I am getting this error while trying to convert a .xls file. Any idea? 

```bash
# unoconv  -f html /var/www/html/resume4/04-17\ gfdgdg\ ffggdf\ req\ update.xls
unoconv: RuntimeException during import phase: Office probably died. Unsupported URL <file:///var/www/html/resume4/04-17%20gfdgdg%20ffggdf%20req%20update.xls>
```

**Comment by shaggyone** [comment]
Same for me. It seems that unoconv server cannot actually be started on a remote server.

**Comment by gumbert** [comment]
@Ranjithkaipra in your case you need to install package libreoffice-calc

**Comment by dagwieers** [comment]
Please read the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) and check the various bullets. In case this problem still exists despite the instructions and using the latest unoconv from the master branch and the latest LibreOffice, feel free to reopen this issue.

Thanks for the feedback !

**Comment by erikig** [comment]
I kept running into this issue when the file in question was not accessible. More often than not it was due to  issues in the filename or path of the file. In the case of @Ranjithkaipra I'd make check the the spaces in that path.

**Comment by blackfan23** [comment]
Same here. I had the very problem while moving from my macOS dev environment to linux node js production server. While Mac's HFS+ (the Mac filesystem) is usually configured to be case insensitive but case preserving, linux is case sensitive. That led to the unoconv crashing on linux, but not on macOS.

**Comment by LiutongZhou** [comment]
Same problem when calling from python subprocess 
```python
subprocess.run(f"unoconv -f docx {local_input_dir}/*.doc ")
```

```
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL </tmp/tmpa8t8wpvg/input/*.doc>: "from LoadEnv::initializeLoading"
```
