### ISSUE TITLE
unoconv supports python 2.6?

### ISSUE THREAD

**Issue by somepalli** [dagwieers/unoconv#233]
i am trying to install unoconv 0.6 in aws which have the python 2.6. is there any version which supports python 2.6?

**Comment by FelixSchwarz** [comment]
I'm using unoconv on CentOS 6 (which has Python 2.6) so I'd say it is support. If you're interested in a (S)RPM please let me know.

**Comment by dagwieers** [comment]
We recommend using the native python that ships with LibreOffice.
See the Troubleshooting section in the README for more information.

**Comment by dagwieers** [comment]
I am going to close this. If you have more information or there is an issue, feel free to reopen the issue.
