### ISSUE TITLE
can not convert odt to ods

### ISSUE THREAD

**Issue by graig** [dagwieers/unoconv#235]
The new file has a file type of ods but it will only open in writer and will not open in calc.

owner@ubuntu-pc:~/temp$ unoconv -vvv -f ods inventory.odt
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=14942)
Input file: inventory.odt
Selected output format: ODF Spreadsheet [.ods]
Selected office filter: calc8
Used doctype: spreadsheet
Output file: inventory.ods
DEBUG: Terminating LibreOffice instance.
DEBUG: Waiting for LibreOffice instance to exit.
owner@ubuntu-pc:~/temp$

**Comment by dagwieers** [comment]
You cannot convert a document-type file into a spreadsheet-type file.
I am surprised LibreOffice did not complain though...

**Comment by graig** [comment]
It would be VERY useful feature to be able convert writer tables to calc files as well as the other way around.
