### ISSUE TITLE
unconv error "The document 'file:///tmp/file.xlsx' could not be opened

### ISSUE THREAD

**Issue by dmix75** [dagwieers/unoconv#237]
When trying to run the following command.

unoconv -f pdf /tmp/file.xlsx

We get back the error "The document 'file:///tmp/file.xlsx' could not be opened.

We have verifed openoffice is running and can be connected to on port 2002 via telnet localhost 2002

It appears to be returning null from "loadContentFromURL".  Any thoughts on what may be the cause?  

We are using LibreOffice 4.3 and unconv 0.6

**Comment by temporaryidea** [comment]
have you solved the problem,give some suggestions?

**Comment by dagwieers** [comment]
Could this be as simple as an access restriction ? (permissions, ownership, SELinux, ACLs)
If not, we should investigate in what situations loadContentFromURL can return null, and improve the error-message (or report upstream).

I wonder if we can get a better error message from the UNO API in this case ?

**Comment by temporaryidea** [comment]
Use libreoffice4.0 version is no problem, python completely do not understand, first to solve it, very grateful

**Comment by dagwieers** [comment]
I need more feedback in order to reproduce this.
Can you please try all the suggestions in the [Troubleshoot instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) section ?

Thanks in advance !

**Comment by dagwieers** [comment]
Feel free to reopen this issue if you have more information.
Thanks !
