### ISSUE TITLE
Unoconv fails with error "Error: Unable to connect or start own listener. Aborting" if LibreOffice has never been run

### ISSUE THREAD

**Issue by rbalint** [dagwieers/unoconv#241]
It fails with the error in the question if it does not find the LibreOffice personal configuration file, but it also creates them before exiting.
The second run succeeds.
You can reproduce the error but removing the personal configuration files, then trying to run unoconv:
 $ rm -rf .config/libreoffice/
 $ unoconv foo
 Error: Unable to connect or start own listener. Aborting.
 $ unoconv foo
 unoconv: file `foo' does not exist.
 ...

**Comment by dagwieers** [comment]
We think we have this one covered now in commit e4f65ed0d23c21e98ef55cbc69b74119bab26b44.
Can you try the latest unoconv from the master branch to see if this is fixed for you ?

Thanks for the feedback !

**Comment by dagwieers** [comment]
My own testing now confirms the fix.
Note the "exit code 81 (new installation)" output.

```bash
[user@moria ~]$ rm -rf .config/libreoffice/
[user@moria ~]$ /opt/libreoffice5.0/program/python /usr/bin/unoconv -vvv -f pdf german_reference.fodt 
Verbosity set to level 3
Using office base path: /opt/libreoffice5.0
Using office binary path: /opt/libreoffice5.0/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /opt/libreoffice5.0/program/soffice.bin.
LibreOffice listener successfully started. (pid=1864)
DEBUG: Caught exit code 81 (new installation). Restarting listener.
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /opt/libreoffice5.0/program/soffice.bin.
LibreOffice listener successfully started. (pid=1871)
Input file: german_reference.fodt
Selected output format: Portable Document Format [.pdf]
Selected office filter: writer_pdf_Export
Used doctype: document
Output file: file:///home/user/german_reference.pdf
DEBUG: Terminating LibreOffice instance.
DEBUG: Waiting for LibreOffice instance to exit.
```

So I am closing this issue. If you still have a problem related to this issue with the latest version from the master branch, feel free reopen this issue.

Thanks for the feedback !

**Comment by cffz0225** [comment]
I also encountered this error, and then according to the above steps, but it is always a new error. the log: 
```javascript
root@95935cb9185f:/usr/lib/libreoffice/program# python3 /usr/bin/unoconv -vvv -f pdf *.txt
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=559)
DEBUG: Process /usr/lib/libreoffice/program/soffice.bin (pid=559) exited with 1.
Error: Unable to connect or start own listener. Aborting.
```
my unoconv version is 
```javascript
root@95935cb9185f:/usr/lib/libreoffice/program# unoconv --version
unoconv 0.6
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4]
LibreOffice 4.2
```
could give me some help? thank you very much.

**Comment by kathiedart** [comment]
Same here if I delete .config/libreoffice then it always fails first time

**Comment by kathiedart** [comment]
If .config doesn't exist then it succeeds, but as other things need it, I can just set HOME=/tmp and it runs fine first time.

**Comment by MingfeiPan** [comment]
encountered this error, i tried "chmod -R 777 .config/libreoffice" then it  works as non root user(set PATH already)

**Comment by aroslov** [comment]
Had the same issue using unoconv with Elastic Beanstalk / Node initially got it fixed via `chmod`, turns out this [NPM package](https://github.com/yeoman/update-notifier) (included in NPM 5) creates `/tmp/.config` (which happens to be the home folder for nodejs user), but does so with root permissions, and libreoffice is unable to write to it. Decided to create it in `.ebextensions`, before NPM gets in the way.

**Comment by LAfricain** [comment]
I have the same issue on Ubuntu 18.04:
`Failed to connect to /usr/lib/libreoffice/program/soffice.bin (pid=18589)`
 with:
```
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
LibreOffice 6.2.3.2
```
And often I need to kill soffice.bin if I want to use again LO.
Please reopend the issue

**Comment by FROGGS** [comment]
Same here. I'm using libreoffice via uniconv in a docker container, and now and again soffice keeps running and prevents further conversions.
The main question is this I guess: Is this a bug in unoconv or in libreoffice?

Since my docker containers run on a server unattended, it takes a while to realize that soffice is hanging.
This is quite problematic for me.

Is there a way to debug this issue? Can we put some debugging stuff into unoconv and let it run for some weeks? (I'd be able to collect the debug messages.)

**Comment by TobiasJu** [comment]
I've got the same issue.
Only running unoconv as root works for me. Which is not the best solution...
