### ISSUE TITLE
How to use unoconv with Windows 7 and python 2.7.9?

### ISSUE THREAD

**Issue by efriossoltero** [dagwieers/unoconv#243]
Hello,

I'm trying to use unoconv with Windows 7 and Python 2.7.9. I already installed LibreOffice 4.4 and UNO 0.3.3 (pip install uno). 

I get this error:

<pre>
C:\Users\user>python "C:\Program Files (x86)\unoconv-0.6\unoconv" -h
  File "c:\Program Files (x86)\unoconv-0.6\unoconv", line 241
    print 'PATH=%s' % os.environ['PATH']
                  ^
SyntaxError: invalid syntax
</pre>

This runs without a problem:
C:\Users\user>python

<pre>
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> 'PATH=%s' % os.environ['PATH']
</pre>

How can I run unoconv? Thanks.

**Comment by dagwieers** [comment]
Sorry, I don't understand that syntax error either. Must be something trivial though :-/

**Comment by regebro** [comment]
That syntax error is likely actually on an earlier line.
