### ISSUE TITLE
Support for pptx docx

### ISSUE THREAD

**Issue by nairmahesh** [dagwieers/unoconv#244]
Wanted to convert the folliowing extensions docx, xlsx, pptx. Does unoconv support it. Didnt see them in the list,

How do we convert these extensions in it?

**Comment by thenadz** [comment]
Why don't you try it? FWIW, docx does work. Can't speak to the others.

**Comment by alvesp** [comment]
Hi guys,

We are using unoconv to do the conversion and it's work. Well it seems to do the job, however there is some details that is missing in pptx, the slide titles are not being passed to pdf, and the bullets are not coming formated.

Any Ideas?

**Comment by dagwieers** [comment]
Please look at the Troubleshooting section. But basically:
 - try it again with the latest LibreOffice.
 - if it fails when exporting using LibreOffice directly, you will have to report it to the LibreOffice project to get it fixed.

Please add a link to your LibreOffice bug-report here, so others with the same issue can find the reference and chime in. Thanks in advance for reporting it upstream !

**Comment by dagwieers** [comment]
I am closing this issue. If you have more information or a link to LibreOffice bug tracker to track this bug upstream I will reopen this bug. Thanks for your feedback.

**Comment by nairmahesh** [comment]
Thanks for your help.

**Comment by nadavkav** [comment]
I am unable to convert PPTX to PDF (I am using Moodle 3.2), so... initially, opened:
https://tracker.moodle.org/browse/MDL-57883
And after some research... found: https://pydio.com/forum/f/topic/unoconv-and-error-l-291/
