### ISSUE TITLE
Row freeze won't survive conversion ods->xls

### ISSUE THREAD

**Issue by jkavalik** [dagwieers/unoconv#245]
I have ods spreadsheet (libreoffice) where Window->Freeze is used to lock header of big table. If I open it in libreoffice and save as xls, then open that xls (in libreoffice or ms excel viewer) header is locked. But if I do "unoconv -f xls file.ods" then the resulting file has header not frozen anymore.

Tried on:
Ubuntu 12.04
unoconv 0.4
python 2.7.3
LibreOffice 3.5

and
CentOS release 5.11
unoconv 0.6
python 2.4.3
OpenOffice.org 3.1

**Comment by dagwieers** [comment]
Since unoconv does not do any manipulations, this bug must exist in LibreOffice.
Have you tried opening in LibreOffice or OpenOffice and exporting manually ?

If this fails as well, you may want to open a support ticket with LibreOffice/OpenOffice to get this problem fixed. (**Reminder** to add documentation on how to report issues to both projects)

**Comment by jkavalik** [comment]
I tried - I open ods in LibreOffice, header is frozen; save as xls, close ods, open xls - still frozen. But when using unoconv it is not - I am not sure how much work unoconv does, I did not try if LO has some sort of direct commandline conversion, only open/save as in normal Calc.

**Comment by jkavalik** [comment]
OK, I tried

    soffice --convert-to xls:"MS Excel 97" test.ods
and results are the same as with unoconv. Sorry for bothering you. Should I report it to LO then?

**Comment by dagwieers** [comment]
Yes, it's best to report it to the LibreOffice bugtracker. Please add the bug number to this thread so others can find it here as well :-) Thanks for reporting ! :+1:

**Comment by dagwieers** [comment]
Please add the bug number/link to LibreOffice tracker. I am closing this issue now until we can track it upstream.
