### ISSUE TITLE
Not able to manage/handle page breaks 

### ISSUE THREAD

**Issue by dinesh-codal** [dagwieers/unoconv#249]
While trying to convert my HTML to PDF I need to control the page breaks like I want from this point of my html doc should start with a new page.

Please let me know if this is possible.

**Comment by dagwieers** [comment]
I just tested this using LibreOffice 4.4.3.1, and it works for this example:

```html
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
  Testing
  <p><!-- pagebreak --></p>·                                                              
  Next page
  </body>
</html>
```

The PDF that results from the below command consisted of 2 pages:

    unoconv -f pdf test.html

Let me know if you have any issues.
