### ISSUE TITLE
ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by SOLDIERz** [dagwieers/unoconv#255]
I get the above error also when I'm trying to explicitly load my custom libreoffice Installation with:

/opt/libreoffice4.3/program/python.bin unoconv -f pdf OpenDocument-v1.0ed2-cs1.odt -vvv

Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted

Any idea why this is happening? When I'm loading the python cli inside the libreoffice Installation the import of encodings works just fine.

**Comment by dagwieers** [comment]
It seems the python from LibreOffice is not able to find its own libraries, I wonder if there is something wrong with the PYTHONPATH that is being set. I have never experienced this myself.

See: http://stackoverflow.com/questions/16511821/py-initialize-unable-to-get-the-locale-encoding-in-opensuse-12-3

Please look at the following list of instructions to make sure we are not forgetting anything obvious:
https://github.com/dagwieers/unoconv#troubleshooting-instructions

And then maybe enable the commented `debug_office()` statements to see what PYTHONPATH is set to.

**Comment by dagwieers** [comment]
If you have more feedback, feel free to reopen this issue.

Thanks for the feedback !

**Comment by klerd** [comment]
Hi there,

I've attempted adding my PYTHON environment variables as follows:

export PYTHONHOME=/usr/local/bin/
export PYTHONPATH=/usr/local/lib/python2.7/:/usr/local/lib/python2.7/lib/:/usr/local/lib/python2.7/lib/site-packages/
export PATH=$PYTHONPATH:$PATH

However I now have this error:

`Error: Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/opt/bitnami/python/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\`

Really quite stumped on this. 

Simply running unoconv to convert a file (from docx to pdf) works fine. And running the command `python` by itself runs python2.7 just fine.

**Comment by pankajr141** [comment]
The issue is due to Pythonpath, faced same issue. 
when executing from python use following
import commands
```
cmd = "export PYTHONPATH=/usr/bin/python3;unoconv -f pdf --output file.pdf file.doc"
command.getoutput(cmd)
```
it will work
