### ISSUE TITLE
Run unoconv with libre on another server

### ISSUE THREAD

**Issue by mknwebsolutions** [dagwieers/unoconv#257]
I assumed that I can run a plain installation of unoconv from one server to another server running libre office in an open socket mode.  Is this even possible?  Why would I need to install i.e. libreoffice extensions if I'm going to be running libreoffice on another server?

**Comment by dagwieers** [comment]
Because we need LibreOffice to connect with the remote listener, unless you want to implement the UNO protocol and object model yourself which we didn't do.
