### ISSUE TITLE
Unoconv requires LibreOffice installed even when connecting to remote listener

### ISSUE THREAD

**Issue by vercotux** [dagwieers/unoconv#260]
When trying to connect (`./unoconv --server 127.153.35.75 --port 2002`) to a listener instance, running on a remote server, the following error is produced:

    unoconv: Cannot find a suitable office installation on your system.
    ERROR: Please locate your office installation and send your feedback to:
           http://github.com/dagwieers/unoconv/issues

Does the client require the entire LibreOffice stack locally when only the remote listener is going to be doing the actual conversions?

From the documentation:
> It is also possible to use a listener or LibreOffice instance that accepts connections on another system and use it from unoconv remotely. This way the conversion tasks are performed on a dedicated system instead of on the client system. **This works only if you have a shared filesystem mounted at the same location.**

What does this mean in concrete terms? Is there any more documentation on the topic? Some examples would be nice.

**Comment by dagwieers** [comment]
You need LibreOffice locally installed in order to connect to the remote instance (and the version should be identical, possibly also the architecture).

Since the file is not being transferred, only the location, the file needs to be locally available as well. (Either transferred or using a network filesystem). Personally I don't think the networked functionality is as useful the way it is conceived.

**Comment by vercotux** [comment]
This is pretty much useless then. It's better to write a custom script that sends the file to the remote server, execute it there and copy back the result.

**Comment by dagwieers** [comment]
Indeed, especially since LibreOffice has issues when handling multiple requests...

**Comment by dagwieers** [comment]
We added support for URLs, so this functionality could be somewhat more useful if the documents are available over HTTP or some other protocol LibreOffice understands.

I am closing this issue, if there is anything relevant to add, please add it here or reopen the issue.
