### ISSUE TITLE
unoconv Office probably died. Unsupported URL..all libreoffice packages have been installed

### ISSUE THREAD

**Issue by TansieChen** [dagwieers/unoconv#264]
Hi,

I have this problem when running unoconv in ubuntu:
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <file:///home/tansie/vehicle-service-record.xls>: "type detection failed"

I installed all the LibreOffice core packages using sudo apt-get install libreoffice, but the problem still exists. 

Thank you.

**Comment by skywinder** [comment]
Hi. Are you sure, that is unoconv, not a LibreOffice? I found, that  exception in LibreOffice sources:

     LoadEnvException::ID_UNSUPPORTED_CONTENT, "type detection failed");

http://docs.libreoffice.org/framework/html/loadenv_8cxx_source.html

**Comment by skywinder** [comment]
And this link could also help https://forum.openoffice.org/en/forum/viewtopic.php?f=20&t=75639
I think the problem in dot in file path.
