### ISSUE TITLE
Is it possible to add metadata to files which are converted to .pdf?

### ISSUE THREAD

**Issue by lastnoob** [dagwieers/unoconv#266]
I dont know where to ask, but is it possible somehow to add metadata to files which are converted to .pdf?
for example if I convert an .rtf file to .pdf and there are predefined metadata for the company, etc, can I add them automatically to the .pdf documents?
Thanks

**Comment by dagwieers** [comment]
It was not possible before, but I just added the necessary functionality to do exactly this. And if it works out well, this will be the first new feature for the upcoming v0.8 release :-)

So please test !

More information in commit 21d4f8aaa69c4b73ef156eed9e52a54ef37a0d77, the documentation has been updated as well. Look at option `-M` or `--meta` !

**Comment by lastnoob** [comment]
Wow! Great!
I will, thank you!

**Comment by dagwieers** [comment]
Any feedback yet ?

**Comment by regebro** [comment]
No response, closing. We can reopen if needed.
