### ISSUE TITLE
DOC/DOCX to PDF conversion error.

### ISSUE THREAD

**Issue by shividhar** [dagwieers/unoconv#275]
Unoconv intermittently fails to convert a relatively large DOC file (~500kb), by unexpectedly shutting down halfway through the conversion. It's a hit or miss as it converts sometimes while other times it doesn't. 

![Error Image](http://i.gyazo.com/8a28165463ff7475aa902f1a73f52cbb.png)

Console get following error: "[Error: unoconv: RuntimeException during export phase:
I20150731-17:52:17.455(-4)? Office probably died. Binary URP bridge disposed during call
I20150731-17:52:17.456(-4)? ]"

Operating System: OS X Yosemite
Libre Office Version: 4.3.7
Unoconv Verison: 0.7

**Comment by dagwieers** [comment]
Please check the troubleshooting section in order to determine whether this is a LibreOffice problem or not.

**Comment by regebro** [comment]
Closing for lack of feedback. This can be reopened if needed.
