### ISSUE TITLE
Conversion of a list from a docx to html

### ISSUE THREAD

**Issue by elmanuelito** [dagwieers/unoconv#287]
Hi
I'm using unoconv 0.6. I'm wondering if lists are properly converted when going from a docx to html.  
I'm using a simple test case with a docx file containing a single list item. It's then converted as:

    <ul>
	    <li/><pre class="western">List item</pre>
    </ul>

Shouldn't the list item be surrounded by an opening an closing "li" tag instead?

I ran into this problem when trying to apply pandoc to a html document generated by unoconv. Pandoc will not detect the list as it is currently returned by unoconv.

Thank you for your help!

**Comment by pquentin** [comment]
@elmanuelito Thank you for your report!

Do you have the same issue when converting manually from LibreOffice? I think so. If this is the case, it's a LibreOffice bug, not a unoconv one.

**Comment by elmanuelito** [comment]
You are right, I'll try to report it to them. Thanks.
