### ISSUE TITLE
Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice

### ISSUE THREAD

**Issue by nwalke** [dagwieers/unoconv#290]
When trying to run `unoconv --version`, I get the following:
```
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```

If I go to `/usr/lib/libreoffice`, I see a program folder with pyuno.so inside.  I'm unsure what to do from here.

This is on an Ubuntu 14.04 box using unoconv commit `f5526cf6888a40069768b0c221df104c286b5cd8` and libreoffice 4.3.

Any help is appreciated

**Comment by pquentin** [comment]
Yeah, the code that detects the various parts of LibreOffice needed for unoconv is a bit brittle. Also, the unoconv maintainer appears to be busy (I won't throw the first rock) so you won't get an easy fix here. Two questions:

 * Are you familiar with Python?
 * What does `find /usr/lib/libreoffice -name python` return?

Thanks!

**Comment by nwalke** [comment]
I was actually able to fix this by changing the first line to `#!/usr/bin/env python3` since I found uno.py under python 3.

**Comment by dagwieers** [comment]
The solution (as explained in the documentation) is to use the python binary that ships with LibreOffice.
There is no other good solution. However, unoconv should be able to find this python binary if it is in one of the known paths.

If the shebang needs to be changed on Ubuntu specifically, it is up to the distribution to ensure it works out of the box though.

**Comment by dagwieers** [comment]
> Also, the unoconv maintainer appears to be busy (I won't throw the first rock) so you won't get an easy fix here.

@pquentin We just released v0.7 in July, so your intel is outdated :-)

**Comment by nwalke** [comment]
@dagwieers This is probably due to us wget'ing a certain commit version of unoconv, not through the distro.

**Comment by dagwieers** [comment]
@nwalke I cannot find that commit version. Do you know whether it is old ? If so, could you please try a newer release, just to test if this is a regression that is already fixed, or a real bug.

**Comment by nwalke** [comment]
I might be incorrect in stating that was a commit number...   The URL we fetch unoconv with is this:
https://raw.githubusercontent.com/dagwieers/unoconv/f5526cf6888a40069768b0c221df104c286b5cd8/unoconv

**Comment by nwalke** [comment]
Actually I was able to find that commit...
```
commit f5526cf6888a40069768b0c221df104c286b5cd8
Merge: d1b75ce 450edcf
Author: Dag Wieers <dag@wieers.com>
Date:   Wed Jul 8 09:21:40 2015 +0200

    Merge pull request #265 from pataquets/master

    Minor readme addition about HOME directory (#87)
```

**Comment by sTb1337** [comment]
I had the same problem. Modifing #!/usr/bin/env python to #!/usr/bin/env python3 in unoconv script fixed the problem.

..:/tmp# find / -name unoconv
/usr/bin/unoconv
...:/tmp# pico /usr/bin/unoconv
...:/tmp# unoconv --show
The following list of document formats are currently available:
  bib      - BibTeX [.bib]
  doc      - Microsoft Word 97/2000/XP [.doc]
