### ISSUE TITLE
Enhancing the performance on converting text files

### ISSUE THREAD

**Issue by Sworddragon** [dagwieers/unoconv#291]
I'm using unoconv 0.7 and I'm noticing that even text files with only 1 character in it are needing over 1 second to be converted into a PDF document with unoconv. That looks really long to me for such a file so maybe it is possible to enhance the performance here.

**Comment by pquentin** [comment]
@Sworddragon are you using a listener?

**Comment by Sworddragon** [comment]
You mean from LibreOffice? Does unoconv also rely on it for text files?

**Comment by pquentin** [comment]
@Sworddragon yes, unoconv "launches" LibreOffice before converting, so there's a startup time that will exist for every file. If that's not acceptable, you can bypass it by using a unoconv listener. It should make things go faster. See https://github.com/dagwieers/unoconv#start-your-own-unoconv-listener

**Comment by Sworddragon** [comment]
Thanks for the information, this is then not a performance issue and I'm closing this ticket.
