### ISSUE TITLE
Running 2+ instances of unoconv concurrently results in error

### ISSUE THREAD

**Issue by ribbles** [dagwieers/unoconv#299]
unoconv v6.6

run the following command 2 2 different shells:

`unoconv -d document -f html -o x.html guide.docx`
`unoconv -d document -f html -o y.html guide2.docx`

Second process exits with:
`unoconv: RuntimeException during update-indexes phase:
Office probably died. Binary URP bridge disposed during call`

**Comment by dagwieers** [comment]
Yes, we know and it is also documented. (Read the README)
And unfortunately there is nothing we can do, it is a LibreOffice/OpenOffice problem.
