### ISSUE TITLE
Unable to use unoconv through php shell_exec

### ISSUE THREAD

**Issue by code-wizard** [dagwieers/unoconv#302]
Hey Guys 

I installed unoconv through terminal using 

sudo apt-get install unoconv

Everything works perfect on terminal when I do

unoconv -f pdf filename.ppt 

but when try doing the same using php 

shell_exec(unoconv -f pdf filename.ppt)

I get the following errors

/usr/lib/libreoffice/program/soffice.bin: /opt/lampp/lib/libldap_r-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
/usr/lib/libreoffice/program/soffice.bin: /opt/lampp/lib/liblber-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
No protocol specified
Failed to connect to /usr/lib/libreoffice/program/soffice.bin (pid=6009) in 6 seconds.
Connector : couldn't connect to socket (Success)
Error: Unable to connect or start own listener. Aborting.

Please what am i doing wrong?

**Comment by dagwieers** [comment]
Please read the README first.

**Comment by code-wizard** [comment]
I have done the following troubleshooting 

Added #!/opt/openoffice4/program/python at the topmost path of unoconv file.

Tried forcing another python 
shell_exec('opt/openoffice4/program/python /usr/bin/unoconv -f pdf $file')

but i get this error 
Error: Unable to connect or start own listener. Aborting.

I must point out that i got this working on windows with the above troubleshooting steps but not on ubuntu.

**Comment by code-wizard** [comment]
I got this working. Had some issues with permissions so i added apache2/www-data/daemon to sudoers.

**Comment by pquentin** [comment]
@code-wizard Did you consider closing this issue?
