### ISSUE TITLE
Unsupported URL error on converting DOCX to PDF

### ISSUE THREAD

**Issue by geraldb-nicat** [dagwieers/unoconv#303]
hi!

i'm trying to use unoconv to convert DOCX-documents to PDF via command-line.

here is what i did:

> sudo apt-get install unoconv
> unoconv -f pdf -o ./test.pdf ./test.docx

this results in the following error:

> unoconv: RuntimeException during import phase:
> Office probably died. Unsupported URL file:///home/vagrant/test.docx: "type detection failed"

i also tried installing the full libreoffice via:

> sudo apt-get install libreoffice

but this didn't solve the problem (and also i would expect unoconv to install all required dependencies itself).

do you have any clues on how to solve this problem? thanks a lot in advance!

best wishes
gerald

**Comment by bkleef** [comment]
@geraldb-nicat same here, any ideas?

**Comment by Calvin92** [comment]
@bkleef Good job. It helps.

**Comment by aislandener** [comment]
@bkleef tks for helping for me

**Comment by chppatel** [comment]
What about in cent os 7?
