### ISSUE TITLE
Formula is not calculated when convert xlsx to pdf

### ISSUE THREAD

**Issue by simkimsia** [dagwieers/unoconv#310]
Using XlsxWriter a python module to generate .xlsx files, converting them into pdf will display cells that have  a formula will end up showing as 0 or empty.

```
unoconv -f pdf spreadsheet.xlsx
```

Is there a way to force unoconv to recalculate the formula before converting into pdf?

**Comment by dagwieers** [comment]
I guess this makes sense if the result is incorrect.
Can you provide me with an example so I can test this ?

We could recalculate by default, or allow for a plugin that does this optionally. (See #84)

Thanks for the feedback !

**Comment by regebro** [comment]
Closing for lack of feedback. This can be reopened if needed.
