### ISSUE TITLE
Give the mimetype / extension source separately (ErrCode 3088)

### ISSUE THREAD

**Issue by Taluu** [dagwieers/unoconv#315]
I am currently running into a 3088 error when trying to convert ppt(x) documents to images (using the html format, then using only the images).

I found out why, it was because my file had a pattern like a hash sha1, without any extensions. When I appended an extension on the filename, it worked as expected.

As this filename format is the one we're using for all other converters mecanisms (such as ghostscript for pdfs), but as I have the extension (And even the mimetype) available, would it be possible to set those on separate options on unoconv ?

Thanks.

**Comment by dagwieers** [comment]
I am willing to accept patches that make this use-case possible, if and only if it doesn't break the old use-cases. But if you suggested change would make it work better out-of-the-box, I don't see why we wouldn't merge this !

Thanks for the feedback. This may actually help other people having 3088 errors !

**Comment by Taluu** [comment]
The thing is, I'm wondering if it is not a limitation from soffice ? Or do you think it could be handled here ?

**Comment by dagwieers** [comment]
That's what we have to find out. Or maybe check with the LibreOffice developers.
Maybe check how LibreOffice handles files with incorrect/missing extensions ?

**Comment by MartijnVdS** [comment]
I've made an option to specify the "import filter name" (#343).

It allows you to set the name of the filter to use for importing the file (most useful if the file doesn't have an extension or comes in from stdin)

**Comment by regebro** [comment]
The import filter name seems to have solved the issue.
