### ISSUE TITLE
Ambiguous message

### ISSUE THREAD

**Issue by alikefia** [dagwieers/unoconv#326]
Situation: Message on startup (as a listener) inside a docker container - "Existing LibreOffice listener found, nothing to do."

Analyse: May be for an unknown reason there is another instance => debug

What I have found: On these two lines, we send **the same messages**:
- https://github.com/dagwieers/unoconv/blob/master/unoconv#L1162: Existing office - WARN (I guess)
- https://github.com/dagwieers/unoconv/blob/master/unoconv#L1187: No except on start - OK (I guess)

Is there any reason why we have the same message, have I missed something

PS: on debug, I understood that I am in the second case (OK) and unoconv stops later...

**Comment by alikefia** [comment]
Update: I am facing #192 on a listener, I will propose a PR for that.

**Comment by alikefia** [comment]
Proposed #327 to manage cold starting of unoconv listener (typically on a docker container)

**Comment by dagwieers** [comment]
Thanks for your contribution !
