### ISSUE TITLE
Some docx files that contained table does not be converted to pdf exactly

### ISSUE THREAD

**Issue by prospdragon** [dagwieers/unoconv#330]
I've installed latest LibreOffice and unoconv.
And tried to convert from docx to pdf.
Some docx files that contained table does not be converted to pdf exactly.
I attached a file.
[test.docx](https://github.com/dagwieers/unoconv/files/182125/test.docx)

**Comment by dagwieers** [comment]
As per the instructions in the README. Did you try this using LibreOffice itself ?
If not, please do. And if it still fails, open an issue with the LibreOffice project.
PS Try using the latest LibreOffice 5.1.x !

**Comment by maganvill** [comment]
@prospdragon 

I'm experience the exact same problem in Linux environment. But the resulting PDF looks great when exporting it manually in LibreOffice (on Windows). 

Did you ever reach a solution?
