### ISSUE TITLE
Please implement a flag to specify location of LibreOffice. "Cannot find a suitable office installation on your system."

### ISSUE THREAD

**Issue by fatuhoku** [dagwieers/unoconv#337]
Hey. Useful project.

I've managed to get LibreOffice & unoconv installed on Heroku with `heroku-buildpack-apt` but was disappointed to find that unoconv trips up on the first hurdle.

`heroku-buildpack-apt` installs LibreOffice here:

```
~ $ which libreoffice
/app/.apt/usr/bin/libreoffice
```

And surprisingly

```
~ $ unoconv
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
~ $ unoconv --help
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```

That's a REALLY unhelpful error.

Countless issues have been raised (#263, #177, #165, #122) just because the path can't be found.

I sort of expected a flag that I could explicitly tell unoconv where my custom location of `LibreOffice` is: something like `unoconv --libreoffice-path /app/.apt/usr/bin/libreoffice`.

Then at least I can get on with my work without being forced to write an issue here on GitHub.

Thanks.

**Comment by jamesrharwood** [comment]
Did you find a solution to this, @fatuhoku? I am having the same issue.

**Comment by jjalan** [comment]
I was able to get pass this error by setting `UNO_PATH` to `/app/.apt/usr/bin/libreoffice`. However, it then complained about `pyuno` missing. I installed `python3-uno`. This threw another error `No module named com`. I am now trying to find an answer to it.

Note, I am trying to set up this on Heroku 16.

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49
