### ISSUE TITLE
Unoconv converting from Word to PDF decimal character issue

### ISSUE THREAD

**Issue by paulggapps** [dagwieers/unoconv#339]
Hi,

I've installed the latest headless version of OpenOffice on my Macbook and a Debian server.

I have a process up and running where a word document is converted to a PDF using Unoconv.

On my Mac, the PDF is converted perfectly.

Whereas on the linux server, a single character is not converted correctly. Everything else is fine, table layouts etc.

For some strange reason the decimal character is rendered as "1/4" instead of "."

The odd thing is that when I copy and paste the "1/4" character into my clipboard and paste into any other document it is actually a decimal "."

I appreciate there are significant differences between a Mac and Debian environments.

Open to suggestions. Any ideas / help would be appreciated.

Thanks

**Comment by regebro** [comment]
Since nobody else has had this problem I'm going to guess that this happen when exporting with Libreoffice directly as well, and so it's not a unoconv issue.

If I'm wrong, please tell me and I will reopen.
