### ISSUE TITLE
problem with encoding (docx -> txt)

### ISSUE THREAD

**Issue by fuelen** [dagwieers/unoconv#340]
Hi.
I have *.docx file with cyrillic symbols and I want to convert it to *.txt.
On my machine with Arch Linux converting works correctly.

```
$ unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/
platform posix/linux
python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0]
LibreOffice 5.0.6.3
```

command

```
$ unoconv --listener & sleep 2 && unoconv -v -f txt -o tmp/file.txt tmp/file.docx`
```

```
file tmp/file.txt 
tmp/file.txt: UTF-8 Unicode (with BOM) text, with very long lines
```

But on the server I run unoconv in docker

`docker run -i --rm -v /long_path:/uploads -v /long_path2:/out site.com:5000/unoconv /bin/bash -c 'unoconv --listener & sleep 2 && unoconv -v -f txt -o /out/file.txt /uploads/file.docx && chown -R 1001:1001 /out'`
and on output i get file without utf-8 encoding (слово -> ?????).

```
$ file  /long_path2/file.txt
file.txt: ISO-8859 text, with very long lines
```

```
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/
platform posix/linux
python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]
LibreOffice 5.1.2.2
```

any ideas?

**Comment by dzmitry-lahoda** [comment]
@fuelen was you able to solve the problem? I have same issue on windows.

**Comment by dzmitry-lahoda** [comment]
try -f text. Seems txt is ansi, text is any. I guess default docs should say text, not txt.

**Comment by fuelen** [comment]
@dzmitry-lahoda unfortunately, I don't remember.

**Comment by regebro** [comment]
Seems to be solved.
