### ISSUE TITLE
Reporting the soffice running without termination

### ISSUE THREAD

**Issue by xjtluapp** [dagwieers/unoconv#342]
Hi All
I would like to report a unoconv remote running issues.
in the moodle page, they recommend us to unoconv for files converting.
https://docs.moodle.org/31/en/Installing_unoconv

it works on a single machine but it has a problem when we decide to use a remote unoconv server for relieving system pressure. 
I tried centos(7.1) and ubuntu(16.04) both, both have the similar problems
![soffice](https://cloud.githubusercontent.com/assets/16590588/16329983/b4ef5cb0-3a18-11e6-8136-4a2c878a81da.jpg)

as you can see in the picture, this happens when the remote unoconv instance does not response in time(which may be caused by network or cpu loading).
![2016-06-24_144339](https://cloud.githubusercontent.com/assets/16590588/16330218/2582ced4-3a1a-11e6-9828-86ab3dc5b8ea.jpg)

 the soffice.bin(libre) is taking 100% CPU resource and never terminated until one manually kill the process with killall command.

I may able to write a script to automatically to kill a 'soffice.bin' program running for a long time, but it is not safe because it will kill all process with in fixed time(for example: 20s, 30s, 40s). in practice, the converting time is based on files uploaded and a fixed time may kill others innocents programs,

I would like to listen yours suggestion.
Thanks

**Comment by dagwieers** [comment]
This is an issue with LibreOffice, not unoconv. Make sure you are using the latest LibreOffice.
If the problem remains, open a bugreport with the LibreOffice project (for the filter plugin you are using)

**Comment by regebro** [comment]
Closing for lack of feedback. This can be reopened if needed.
