### ISSUE TITLE
Cannot find a suitable pyuno library and python binary combination in /Applications/OpenOffice.app/Contents

### ISSUE THREAD

**Issue by shootnix** [dagwieers/unoconv#349]
Hi, my configuration is:
mac os 10.11, unoconv installed via homebrew. OpenOffice is in /Applications/OpenOffice, pyuno.so was installed in /Applications/OpenOffice.app/Contents/MacOS/pyuno.so.
I've tried to put this path into unoconv, does not work. I've tried to copy all libs from MacOS to Contents, doesn't work. Now, I'm running out of any ideas. Please, help!
unoconv in /usr/local/bin/unoconv. 
python 2.7

Error, when I try to run unoconv is:

> unoconv: Cannot find a suitable pyuno library and python binary combination in /Applications/OpenOffice.app/Contents
> ERROR: dynamic module not initialized properly

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by r-martins** [comment]
Duplicated #49

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49
