### ISSUE TITLE
Add an --stdin option to read content from stdin

### ISSUE THREAD

**Issue by dagwieers** [dagwieers/unoconv#35]
Someone request to be able to pipe a document to standard input for doing conversions. Much like the ```--stdout``` option, we could implement an ```---stdin``` option.

**Comment by pataquets** [comment]
There are 2 different PR with proposals for stdin.
@dagwieers: Could you please provide feedback to allow further progress? Thus, interested people can focus on improving and testing. TIA.

**Comment by dagwieers** [comment]
Yes, this one can be closed. Seems to work very well, I am pleased !
