### ISSUE TITLE
Cannot open password protected files even if password is known

### ISSUE THREAD

**Issue by monomelodies** [dagwieers/unoconv#357]
I needed to programmatically strip the password from an office doc (.xlsx in my case, but shouldn't matter). I noticed the help says one may pass --password, but in the code it's commented out. It was also attempting to pass the password protecting single sheets instead of the whole file (which makes much more sense IMO for this feature).

After hacking around a bit, I got it to work. Shall I submit a PR? I realise this changes the possibly intended working of the feature, but since it didn't, ehm, work in the first place I don't think that's an issue.

Cheers,
Marijn

**Comment by monomelodies** [comment]
Sod it, I made a pull request. I think it should be merged ASAP, it makes the feature work as advertised.

**Comment by regebro** [comment]
This was merged.
