### ISSUE TITLE
unoconv: Cannot find a suitable office installation on your system.

### ISSUE THREAD

**Issue by esaruoho** [dagwieers/unoconv#361]
i'm running on macOS Sierra, and have LibreOffice.app in /Applications .
Seems to be version 5.2.2.

Unoconv says:

> unoconv: Cannot find a suitable office installation on your system.

What should I do now? :)

**Comment by justuswilhelm** [comment]
Same issue with
```
$ which soffice
/usr/local/bin/soffice
$ soffice --version
LibreOffice 5.2.3.3 d54a8868f08a7b39642414cf2c8ef2f228f780cf
```

**Comment by dg92** [comment]
@esaruoho @justuswilhelm  any success ?

**Comment by SainteCelery** [comment]
Has anyone discovered a solution?

**Comment by sebma** [comment]
Hi,

I have the same pb.

**Comment by regebro** [comment]
You need to run unoconv with the same Python as the one that Libreoffice runs with. On MacOS, that typically means you have to specify the special Python inside the Libreoffice installation.

    /path/to/Libreoffice/program/python /usr/bin/unoconv ...

If the Libreoffice is installed in a non-standard place you also need to specify the UNOPATH, ie:

    UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ...

See issue #49 for more discussion.

**Comment by denissepacheco** [comment]
> You need to run unoconv with the same Python as the one that Libreoffice runs with. On MacOS, that typically means you have to specify the special Python inside the Libreoffice installation.
> 
> ```
> /path/to/Libreoffice/program/python /usr/bin/unoconv ...
> ```
> 
> If the Libreoffice is installed in a non-standard place you also need to specify the UNOPATH, ie:
> 
> ```
> UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ...
> ```
> 
> See issue #49 for more discussion.

Can you explain how?

**Comment by regebro** [comment]
That is the explanation. I'm not sure what is unclear.

**Comment by himanshurawlani** [comment]
There is no python executable in `/usr/lib/libreoffice/program` for me. Is there something that I'm missing?

**Comment by mascai** [comment]
I have the same error in my docker-container ```python:3.9-slim-bullseye```
How can i specify python version?

More details: https://stackoverflow.com/questions/72746661/how-to-add-doc2pdf-to-custom-docker-container
