### ISSUE TITLE
Is this project still useful? Why not using libreoffice command line?

### ISSUE THREAD

**Issue by slorber** [dagwieers/unoconv#364]
Hi,

Thanks for making this project available to the community and maintaining it over time

As I have a requirement for being able to convert automatically documents to pdf in my servers, I wonder if unoconv is advised for new deployments.

It looks to me that modern versions of OpenOffice and LibreOffice have command line utilities that permit to do the conversion directly (at least LibreOffice has). I am wondering what are the advantages of going through Unoconv.

Also, I'm wondering if someone should rather use OpenOffice other LibreOffice, as it seems LibreOffice gets merged many code coming from OpenOffice, so LibreOffice looks to me like an OpenOffice with more features.

It would be nice to have high-level guidance on the readme on which lib to use for which usecase. In my case I'm going with LibreOffice command line directly, but I don't have the background to know if this is the wisest choice

**Comment by guettli** [comment]
Hello, anybody out there? No answer since two years. It would be nice of the developers could tell is why unoconv is useful. I guess it is, otherwise you would not spend you time on it. Thank you very much.

**Comment by robsco-git** [comment]
Attempting to convert two documents concurrently using the standard LibreOffice method will cause one of the two to fail. Only one instance of LibreOffice can be running on a system at any given time. If your requests to LibreOffice are synchronous, you should be fine using it directly. Another advantage of unoconv is that you can run it in a daemon mode that should reduce the time required for each conversion. The stdin and stdout feature sounds nice as well. No need to handle temporary files.

**Comment by guettli** [comment]
@robsco-git thank you for explaining the benefits. Maybe it would be wise to write these benefits into the README. I think this should be at the top of the README.

**Comment by regebro** [comment]
The command line also seems to lack some options. But I would say, if you can use the commandline directly, do so.
