### ISSUE TITLE
can't find the system path (moodle) in website

### ISSUE THREAD

**Issue by FinalRule** [dagwieers/unoconv#371]
I had a moodle site (fajr.com/fajr-online) I can't find the right system path for unoconv 
so the annotate pdf don't work at all

**Comment by brianlmerritt-kent** [comment]
You need to 

1. Make sure libre or open office are installed correctly
2. Install unoconv
3. In Site Administrator set the unoconv system path.

Have a look at https://docs.moodle.org/31/en/Installing_unoconv if you get stuck
