### ISSUE TITLE
UNOCONV on Moodle 3.2, Windows 2012 server

### ISSUE THREAD

**Issue by spchristy** [dagwieers/unoconv#373]
I'm having issues with unoconv within Moodle.  When I run the “test unoconv path” test in the admin panel it says that, “The unoconv path appears to be properly configured.” But when I click to download the test document it says, “Failed to load PDF document.”  It appears that no document is being created.
Unrelated, but the test script for ghostwriter works fine.

Within the Annotate PDF feature in Moodle, it works fine if a student uploads a PDF file assignment, but if they upload a different document type (ie .docx) it of course does not work. It doesn’t throw any errors, but the page loads into the annotate PDF window as a blank page. 

I tried using unoconv to do a document conversion on the server using the command line option (unoconv -f pdf _________.docx) to see if it would work and it performs the conversion just fine. Using the CLI option I can also convert pretty much any file type perfectly -  .odt,  .doc, .docx, .xls, .xlsx, etc.

I am running Moodle 3.2 on a Windows Server 2012 RS, PHP version 5.6.29, and mssql for the dbase. LibreOffice is version 5 and unoconv is v.7.

Any suggestions as to where to look to solve this problem? I'm guessing it may be a folder/file permissions problem or something like that. What folders does unoconv use during the conversion process? Any help you can offered would be greatly appreciated as I'm out of ideas for where to look.

Thanks!

**Comment by spchristy** [comment]
Still looking for answers to this problem. Anyone out there????

**Comment by eduham** [comment]
@spchristy same problem here with moodle 3.1.3+

Have you found a solution now?

**Comment by spchristy** [comment]
Nope. I gave up on getting it to work on a Windows server. We upgraded to Moodle 3.3 and are using the Google Document converter feature instead. It seems to work well.

**Comment by larryelliott** [comment]
I hope this helps someone else. I ran into a similar problem, but our environment is Linux. Despite the differences in Windows and Linux, the solution for me was to get a service running the unoconv --listener. Here is where I found the solution for Linux: https://docs.moodle.org/31/en/mod/assign/feedback/editpdf/testunoconv/upstart

**Comment by dagwieers** [comment]
So I wonder what my role is to unoconv. It seems to make more sense if the moodle developers (or anyone who has a direct interest in it) takes over managing this project. Because I am not really managing it anymore.

**Comment by regebro** [comment]
This does seem to be a moodle config issue, though. Closing.
