### ISSUE TITLE
: No such file or directory

### ISSUE THREAD

**Issue by cff2007** [dagwieers/unoconv#374]
unoconv -f pdf /root/src/unoconv/1.txt
I am sure the /root/src/unoconv/1.txt file is exist
the result is
No such file or directory
unoconv -h
the result also
No such file or directory
my system is centos6.8 Linux  2.6.32-642.13.1.el6.x86_64
the verion of openoffice is 4.1.3
How to solve this problem?

**Comment by regebro** [comment]
No idea, I can't reproduce that error. If the file doesn't exist you actually get another error, likewise if you can't read it. So, no clue what is going on here.

**Comment by regebro** [comment]
Your unoconv installation is broken, try to reinstall it.
