### ISSUE TITLE
copying text filter option for pdf not working

### ISSUE THREAD

**Issue by hasanhameed07** [dagwieers/unoconv#376]
EnableCopyingOfContent=false is not working, I am able to copy text with the following command:

`sudo python3 /opt/unoconv -f pdf -e RestrictPermissions=true -e PermissionPassword=test -e Printing=0 -e Changes=0 -e EnableCopyingOfContent=false -e EncryptFile=true -e DocumentOpenPassword=test Template.doc `

**Using:**
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4]
LibreOffice 5.2.4.2

**Comment by regebro** [comment]
This works for me. Many PDF readers do not respect this flag, that could be the reason. When opened directly with Google Chrome, I could copy with `-e EnableCopyingOfContent=true` and I could not copy with `-e EnableCopyingOfContent=false`, so I think this works.
