### ISSUE TITLE
Using Unoconv in Lambda

### ISSUE THREAD

**Issue by nford** [dagwieers/unoconv#377]
Can it be done self-contained (not using remote LibreOffice instance) given the  Lambda archive limit of roughly 260MB unzipped?

**Comment by kjvenky** [comment]
@nford Did you find a way to install libreoffice in lambda? Is it possible to use libreoffice like phantomjs bin on lambda?

**Comment by mrzenun212** [comment]
@nford @kjvenky did you guys solved this problem?

**Comment by kjvenky** [comment]
@mrzenun212 No I have started using something else. Its working well for me. I can help you with it, my skype id: kjvenky

**Comment by mrzenun212** [comment]
@kjvenky Hi, I already added you on skype, my skype id: zenun1995. Hoping for your response. Thanks by the way!

**Comment by regebro** [comment]
Seems solved.

**Comment by vmesel** [comment]
@regebro actually is not solved. What would be all the necessary binaries to run the unoconv on lambda? How can we work on it so we can get closer to a solution that can be put on a serverless env?

```
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```

This is the output I get only installing the Python Library.

**Comment by regebro** [comment]
You need a full installation of LibreOffice. There are some documents on how to achieve that, but it seems rather involved. Also remember, this means you need to, everytime you run the function that uses unoconv, start LibreOffice. It seems to simply be the wrong solution, to be quite honest, as it kinda defeats the whole Lambda principle.

I think the correct solution here is to run LibreOffice as a server on, say EC2 or something, and then make calls that way. I do want unoserver (the unoconv replacement) to use RPC, which would enable that, but we don't need it at my job, so I haven't had time to implement it. Help with that would be appreciated, it's probably not very difficult.
