### ISSUE TITLE
PPT to PDF: Textboxes underneath images appearing on top of image

### ISSUE THREAD

**Issue by datermine** [dagwieers/unoconv#378]
I have a process that uses unoconv to convert PowerPoint presentations to PDFs (and then eventually PDFs to images), but quite often I have these sorts of artifacts where slide template textboxes are appearing on top of images that would normally occlude them.

For example:
https://storage.googleapis.com/spork-user-media/prezx-9un783nukr7pevu1ce8c9pb9
https://storage.googleapis.com/spork-user-media/n3logrjnc5aj1zw5rhjafko6r.pngquant.png

Is this a known issue? Is there a way to fix this?

**Comment by Aabir1** [comment]
@datermine did you get any solution or any alternate way to do this. I also stuck in similar problem.

**Comment by datermine** [comment]
@Aabir1 -- Yup. I switched to using headless LibreOffice. 

`/usr/bin/soffice --headless --convert-to pdf test.key --outdir .`

FYI - It's been giving me trouble with Keynote files though:

https://stackoverflow.com/questions/44618379/headless-soffice-fails-silently/44807712#44807712

**Comment by dagwieers** [comment]
@datermine It seems strange that a direct conversion using soffice --headless would work correctly in this case. Could you by any chance have upgraded LibreOffice in the process ? Because this seems like a bugfix in LibreOffice, unoconv really doesn't do anything but call LibreOffice. (This is explained in the documentation)

**Comment by datermine** [comment]
If that's the case, then I have no idea how this got solved for me. I made the switch to calling soffice directly a little while ago and don't recall everything I did in the process.

@Aabir1 - perhaps you could let us know if soffice fixed your issue?
