### ISSUE TITLE
Cannot convert encoded text to PDF

### ISSUE THREAD

**Issue by niggli** [dagwieers/unoconv#384]
I am running unoconv V0.7 on OS X Sierra with LibreOffice 4.2.5.2 and I'm trying to convert a encoded text file to a PDF. I run the following command:

`phyton unoconv -f pdf -i FilterOptions=38 example.txt`

[example.pdf](https://github.com/dagwieers/unoconv/files/885167/example.pdf)
[example.txt](https://github.com/dagwieers/unoconv/files/885166/example.txt)

However the output is always the same, the non-ascii characters are all "???????".

In the LibreOffice GUI it's no problem to import such a file, I can select the encoding in the import dialog. Then I can export as a PDF, the result is perfect. However it's important to select "Text Encoded" as the input file format, if you select "Text" then you have the same effect as in unoconv. Probably unoconv suffers under the same problem? How can I force unoconv to use the "Text encoded" input file format?

**Comment by dagwieers** [comment]
Reading the unoconv manual could help.

**Comment by niggli** [comment]
Thanks for the nice comment. I did read the man pages and the readme on github back and forth and tried for hours everything I could find online about the input filters - before I opened this issue. It would be helpful if you could point me at the part of the manual which would help me, thanks.

**Comment by belegnar** [comment]
Text should be utf-8 encoded

**Comment by regebro** [comment]
That seems to be the solution. Thanks.
