### ISSUE TITLE
0.7 not published on pypi

### ISSUE THREAD

**Issue by bengourley** [dagwieers/unoconv#388]
Hi. Could you publish 0.7 on pypi so that I can install it with pip please? Many thanks.

_Edit: v0.7 is not actually working for my use case (binary data via stdin) so releasing 0.7 would be unnecessary for me. How about a new release?_

**Comment by jdgvt81** [comment]
From reading https://github.com/dagwieers/unoconv/releases/tag/0.8.2, looks like maybe this can be closed?
