### ISSUE TITLE
Cannot find a suitable office installation on your system if I use php

### ISSUE THREAD

**Issue by napasa** [dagwieers/unoconv#389]
Hi. I use cmd to execute unoconv command, it works properly, if I use php to invoke unoconv, it complains that "Cannot find a suitable office installation on your system"

**Comment by regebro** [comment]
It could be that the paths are different.
How does the command you run look?

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49
