### ISSUE TITLE
Error While converting PDF to HTML

### ISSUE THREAD

**Issue by bhagwats** [dagwieers/unoconv#393]
[root@localhost html]# **unoconv  --format=html Resume.pdf** 
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1098, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store <file:///home/www/html/Resume.html> failed: 0xc10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1369, in <module>
    main()
  File "/usr/bin/unoconv", line 1285, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1100, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/opt/libreoffice5.3/program/uno.py", line 504, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
+++++++++++++++++++++++++++++++++++++
[root@localhost html]# **unoconv --version**
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.3 (default, May  4 2017, 01:06:08) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
LibreOffice 5.3.3.2

**Comment by regebro** [comment]
Libreoffice can't convert PDF to HTML. It treats PDF imports as graphics, and HTML is a document format, so it can't convert it. Sorry.
