### ISSUE TITLE
docx to html embeding images

### ISSUE THREAD

**Issue by pakizito** [dagwieers/unoconv#398]
Hi all,
Is there a way to disable the generation of embedded images when exporting to html? (A setting or something like this)
Seems like the webmail clients do not like this.

Thank you very much.

With kind regards,
Rodrigo

**Comment by regebro** [comment]
Webmail clients are quite finicky as a general rule. Almost any generic HTML needs too be changed. I believe there are libraries and maybe even commands to help with this.

**Comment by regebro** [comment]
Closed for lack of feedback.
