### ISSUE TITLE
unoconv includes deleted text when converting from doc to txt

### ISSUE THREAD

**Issue by vincentbernat** [dagwieers/unoconv#40]
Hi!

When a `.doc` file with recorded changes is converted to a `.txt`, deleted text appears in the converted version. The same happens when using LibreOffice directly but a work around is to disable the "Show changes" option in LibreOffice menu. There is no such option with unoconv.

(This bug was originally reported to Debian BTS as bug [#624295](http://bugs.debian.org/624295))

**Comment by bulletmark** [comment]
I converted a heap of word docs to pdf using unoconv and found all output files were showing deleted text. Found this bug and applied the patch manually to fix the problem. It would be good to get his fix released.

**Comment by vincentbernat** [comment]
Hey!

The patch is in Debian since July 2013 and nobody complained. It is now in a stable release too. I think you can merge it.

**Comment by skywinder** [comment]
@vincentbernat Hi. I also test it a bit - it seems, that it's works as expected.
I'm waiting of @dagwieers approve to release new version of unoconv. 
And can also include this fix there as well.
@dagwieers what do you think about it?

**Comment by dagwieers** [comment]
I guess we can add it as the default. And people who do want to old behaviour can write a plugin to do the opposite (once we have the plugin/extension system integrated in v0.8).

**Comment by Yichen-fqyd** [comment]
Hi, when I was using the unoconv to convert from word to pdf, the changes(deleted text) is still included, is there any way to solve this problem??
