### ISSUE TITLE
Compare docs

### ISSUE THREAD

**Issue by gitrago** [dagwieers/unoconv#400]
I want to generate a "redline" view of a document where changes against another document version are highlighted or marked with red strikethrough: http://tinyurl.com/y7zj36nj This view can be generated in LibreOffice menu: Edit / Compare Document.  Are there parameters to open a document along with its earlier version **and then** export as pdf?

**Comment by gitrago** [comment]
http://win32com.goermezer.de/openoffice/compare-documents-and-show-diff-in-pdf-with-pyuno.html

**Comment by atrauzzi** [comment]
I know this is an old issue, but has this functionality ever been surfaced in the unoconv command without having to write a separate python script?
