### ISSUE TITLE
unoconv from pptx, text is rendered as image

### ISSUE THREAD

**Issue by Daxten** [dagwieers/unoconv#401]
Hi,
if I export my pptx from libreoffice with dpi-setting of 300 everything stays sharp,
I tried to do the same using unoconv but can't get it to export anything which would be sharp on a HD Display

unoconv -f pdf -e ReduceImageResolution=true -e MaxImageResolution=1200 -e UseLosslessCompression=true -e PageRange=3-3 -e Quality=100 -e ExportFormFields=false Titel.pptx

also the pdf seems to be made out of Images and not real text, which is part of the problem I think

**Comment by Daxten** [comment]
is more information required / is this a known limitation / can I help somehow?

**Comment by dagwieers** [comment]
Have you read the README Troubleshooting section ? This is almost 100% certain a problem in LibreOffice and if you want this to be fixed, you have to report it there.
