### ISSUE TITLE
UnoException during import phase: The document could not be opened

### ISSUE THREAD

**Issue by csotelo8885** [dagwieers/unoconv#402]
Hi,

I've tested unoconv and works fine converting doc,docx and txt files. But when I try to convert pptx files: the following message appears: 

```
unoconv -f pdf /var/www/docs/MyFile.pptx
unoconv: UnoException during import phase:
The document 'file:///var/www/docs/MyFile.pptx' could not be opened.
```

My unoconv version is:

[root@ ]# unoconv -V
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.0 (default, Apr 25 2017, 23:28:40)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
LibreOffice 5.2.7.2

How can I fix that?

Thanks in advance

**Comment by regebro** [comment]
Is that any pptx file or just that one? Can soffice open it?

**Comment by regebro** [comment]
Closing for lack of feedback.
