### ISSUE TITLE
Cannot find a suitable pyuno library and python binary - a newbie

### ISSUE THREAD

**Issue by nattyseydi** [dagwieers/unoconv#405]
Hi, I am a newbie. I have a directory with 140 pdf, I was looking a command who will help to convert all these files in one shot. I find "unoconv". After clonig it Ihave this error message "Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice".

There is lot of issues talking bout it, I tried what other people suggest but it's still not working. I am on ubuntu 16.04
 Any help will be grateful. I am a newbie...

**Comment by pikhovkin** [comment]
Try to copy from /usr/bin/unoconv to /usr/local/bin/unoconv.
And try to replace #!/usr/bin/env python3 on #!/usr/bin/python3 in unoconv file.

**Comment by efinal** [comment]
thanks, it works though I don't know why...

**Comment by younismahsud** [comment]
> Try to copy from /usr/bin/unoconv to /usr/local/bin/unoconv.
> And try to replace #!/usr/bin/env python3 on #!/usr/bin/python3 in unoconv file.

This also worked for me. Thank you.

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49

**Comment by Garibaldy** [comment]
> Try to copy from /usr/bin/unoconv to /usr/local/bin/unoconv. And try to replace #!/usr/bin/env python3 on #!/usr/bin/python3 in unoconv file.

i just fixed adding /usr/bin to path enviroment
