### ISSUE TITLE
PPT changing color while converting with Unoconv

### ISSUE THREAD

**Issue by grlsquared** [dagwieers/unoconv#406]
I am converting PPT to PDF using Unoconv on my Ubuntu 14.04 server. Most of the files are being converted correctly, except few files. After conversion, the color of the slide becomes very bright. It may be CMYK to RGB issue but I am not sure. Is there a way to preserve the colors? 

Command I am using to convert PPT to PDF is:
`unoconv -f pdf PPT_File_Name`

Note: When I open the PPTx in "Microsoft Office PowerPoint" it appears correct, but when I open the same PPTx in "OpenOffice Impress" it appears same very bright color as it was after conversion.

Color before conversion:
![before](https://user-images.githubusercontent.com/16396895/28920415-bdb5d4e6-781f-11e7-8678-28fd1b1c979a.PNG)

Color after conversion:
![after](https://user-images.githubusercontent.com/16396895/28920416-bdb6a614-781f-11e7-8a18-4a338fcaee27.PNG)

Source PPTx file:
[source.pptx](https://github.com/dagwieers/unoconv/files/1197042/source.pptx)

**Comment by dagwieers** [comment]
Have you read the README Troubleshooting section ? This is almost 100% certain a problem in LibreOffice and if you want this to be fixed, you have to report it there.
