### ISSUE TITLE
unoconv on Travis CI

### ISSUE THREAD

**Issue by keshrath** [dagwieers/unoconv#407]
I'm trying to use unoconv on Travis CI, but with very little success. I'm always getting the same error response. Can anybody help me?

`unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice`

.travis.yml

```
language: python

python:
  - "2.7"
  - "3.4"

notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y unoconv

install:
  - pip install codecov
  - pip install .

script:
  - coverage run ./tests/test_converter.py

after_script:
  - codecov
```

Link: https://travis-ci.org/keshrath/pdfconv

**Comment by regebro** [comment]
Is the libreoffice and python3-uno packages installed?

**Comment by keshrath** [comment]
I tried a few things back then, but nothing worked. meanwhile this is no longer an issue for me because this project is no longer being developed further. But I could well imagine that it still doesn't work, but I can't confirm that.

**Comment by regebro** [comment]
Thanks for the respons. We are using Travis to test unoconv, so we know it works in that case, but we download and install specific Libreoffice versions, so it's not the same setup. It also takes absurdly long to do so, so it's not a good workaround.
