### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by regebro** [dagwieers/unoconv#411]
This project has 144 issues open, and no code changes for two years, and the last release isn't even on PyPI.

As a maintainer of several modules myself I understand it's hard to get time to maintain all the libraries, but perhaps the users of the module could help? Maybe even hand the keys over to someone else?

**Comment by dagwieers** [comment]
Sure, I proposed this a few times, nobody took the bait.

**Comment by regebro** [comment]
OK, I'm taking it. :-)

**Comment by dagwieers** [comment]
Done, you're collaborator #2 !

**Comment by dagwieers** [comment]
BTW I registered the unoconv project, but we never migrated to it. We can still do that now. This repository would then move to https://github.com/unoconv/unoconv
