### ISSUE TITLE
Converting password-protected DOCX to PDF behaves differently from DOC to PDF

### ISSUE THREAD

**Issue by Janiczek** [dagwieers/unoconv#418]
If I try to convert read-password-protected **DOC to PDF**, the operation **fails**. Converting read-password-protected **DOCX to PDF** doesn't fail, but **returns gibberish**. It would be nice if it failed too.

Here are the files: [protected.zip](https://github.com/dagwieers/unoconv/files/1421864/protected.zip)
(The password is `s`, if needed)

**Comment by regebro** [comment]
Thanks! 

It seems newer versions of Libreoffice will give an error in both cases. I tried your files with Libreoffice 6. I got different errors, but at least errors. :-) The output file was not created in either case.

DOC: 
```
unoconv: UnoException during import phase:
The document 'file:///tmp/protected.doc' could not be opened.
```

DOCX:
```
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <file:///tmp/protected.docx>: "type detection aborted"
```
