### ISSUE TITLE
Error: Unoconv failed to transcode file

### ISSUE THREAD

**Issue by vtumialan** [dagwieers/unoconv#420]
I have Unoconv on a website with PHP (codeigniter). On my local server (ubuntu) it works perfect, but when I have it on a server in the cloud (ubuntu) it goes wrong when sending transcode.

Type: Unoconv \ Exception \ RuntimeException

Message: Unoconv failed to transcode file

How could I know if it is configuration, permissions or I need to install something on the server?

**Comment by sentiasa** [comment]
@vtumialan - I am experiencing the exact same error; works on my VM (which is Virtual Box, Homestead) but not on AWS. 

Did you figure out how to overcome the issue? Was that a permission issue?

Also I can confirm that unoconv exists in `/usr/bin/unoconv`

Thanks in advance

**Comment by bertalanimre** [comment]
Answered in this issue: https://github.com/dagwieers/unoconv/issues/434

**Comment by regebro** [comment]
Yup, it's a duplicate of #434 indeed, thanks.
