### ISSUE TITLE
How to respect (JPG) image rotation when converting to PDF

### ISSUE THREAD

**Issue by abias** [dagwieers/unoconv#427]
Hi Dag,

We are running unoconv with LibreOffice 5.4.3 as a document converter behind our Moodle learning management system (see https://docs.moodle.org/32/en/Universal_Office_Converter_(unoconv) for details). Moodle leverages Unoconv to convert all types of input documents to PDF which it then continues to process internally. This process works quite fine.

However, we have now seen problems with input files of type JPG which have a rotation set in their EXIF attributes, i.e. the image is stored in landscape format, but the viewing program rotates it on-the-fly before it is displayed. This storing strategy seems to be quite common with consumer cameras and smartphone cameras.

When asked to convert such a file to PDF, Unoconv does not respect the image rotation and just places the image onto the canvas as is it stored in the image file.

I am unsure who is to blame about this, Unoconv or Libreoffice?
I have also noticed issue #116, but I think that this is a different issue here as Unoconv / Libreoffice should just respect the existing image rotation and I don't want to force a particular canvas orientation.

Any help / hint how to solve this issue would be appreciated.

Thanks,
Alex

**Comment by regebro** [comment]
This is Libreoffice that makes that, Unoconv just passes the files to it for conversion.

Using Libreoffice to put a JPG into a PDF is massive overkill, a bit like shooting mosquitoes with a gun, you don't have much control over the outcome. It's better to use software dedicated to image or PDF conversions. I think Imagemagick can do this, but I'm not sure.
