### ISSUE TITLE
Is It possible to work with unoconv on server without GUI?

### ISSUE THREAD

**Issue by Domoryonok** [dagwieers/unoconv#429]
is It possible to work with unoconv on server without GUI?

I got this error:
`Unable to store document to file:///home/somefile.pdf (ErrCode 19468) `
when trying to execute unoconv command:
`unoconv -f pdf somefile.pdf `

**Comment by PABourdin** [comment]
Hi, even though I have nothing to do with `unoconv` (other than using it), your problem looks very much like you do not have permission to write the file to `/home`, which is usually the case if your are not logged in as Administrator... ;-) Probably you can write the file, if you are in another directory.

**Comment by regebro** [comment]
Yes, Unoconv always runs Libreoffice without a GUI, and it works fine on servers. As PABourdin mentioned, that looks like a permission error, or maybe the path doesn't exist. Feel free to open a new issue if you still have problems.
