### ISSUE TITLE
DOCX to PDF using template

### ISSUE THREAD

**Issue by DavidAyliffe** [dagwieers/unoconv#430]
Is there any way to convert from DOCX to PDF and apply a template to the PDFs produced?

I'm trying:

unoconv -f pdf $docxfilenamehere -t tempate.dotx

but get an error

unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <-t>: "from LoadEnv::initializeLoading"

should I give up?

**Comment by abdrmdn** [comment]
looking for the same answer as well.
is there an example or something?

**Comment by regebro** [comment]
This works for me:

`unoconv -t templatefile.ott -o output.pdf input.docx`

The input filename is always last. Yeah, that can be confusing.

**Comment by DavidAyliffe** [comment]
thanks
