### ISSUE TITLE
ERROR: No module named 'uno'

### ISSUE THREAD

**Issue by tonymj76** [dagwieers/unoconv#437]
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

    UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....

Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

See issue #49 for more discussion.
