### ISSUE TITLE
unoconv: Cannot find a suitable office installation on your system.

### ISSUE THREAD

**Issue by svdmitrij** [dagwieers/unoconv#440]
While call unoconv get the error.
Libreoffice binary on my system is **/usr/bin/libreoffice**, Ubuntu 18.04

**Comment by int-ua** [comment]
Libreoffice 6.0?

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49
