### ISSUE TITLE
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice

### ISSUE THREAD

**Issue by teboraqtester** [dagwieers/unoconv#443]
I am getting error when i trying to run 
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named 'uno'
unoconv (0.8.2) is installed .. 

help pls
thanks

**Comment by githublovered** [comment]
maybe is faild to load pyuno module,you cloud try  #/opt/libreoffice6.0/program/python.bin unoconv -f pdf test-file.odt

**Comment by dokw** [comment]
try to change shebang of /usr/bin/unoconv to this: 
`#!/usr/bin/env` `python3`
or to this:
`#!/usr/bin/env python3.5`

**Comment by VasLem** [comment]
Changing `#!/usr/bin/env python3` to `#!/usr/bin/env python3.6` solves the issue for me on Ubuntu 18.04

**Comment by mohammedyunus009** [comment]
That still didnt solve my problem , Im using conda(for python) environment ,also tried `pip install unoconv` , nothing helped

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49

**Comment by lyterati** [comment]
> I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:
> 
> ```
> UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
> ```
> 
> Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.
> 
> Further discussion on #49

Hi @regebro There is no python in Libreoffice/program.

**Comment by letsolexandr** [comment]
If you use venv.

cp /usr/lib/python3/dist-packages/unohelper.py   ../env/lib/python3.6/site-packages/
cp /usr/lib/python3/dist-packages/uno.py   ../env/lib/python3.6/site-packages/

**Comment by regebro** [comment]
@letsolexandr That generally does not work, as you also need some c-libraries. And copying them will only work if you are running exactly the same versions of Python.

It's better to just install unoconv with the pythons used to run Libreoffice. 
To find which Python to use to run unoconv, you can try a script I made.

```
cd /tmp
wget -l https://gist.githubusercontent.com/regebro/036da022dc7d5241a0ee97efdf1458eb/raw/1bc0655423d196acd79a5d9fa60d2baada8dd534/find_uno.py
python3 find_uno.py

```
It should list all Pythons that have a Libreoffice installed.
