### ISSUE TITLE
ODT to PDF conversion freezes

### ISSUE THREAD

**Issue by stschindler** [dagwieers/unoconv#448]
I've encountered a problem with converting an ODT file to a PDF file using unoconv. The command line is as follows:
```
unoconv -f pdf -vvv directive_1640_56.odt
```

Output:
```
Verbosity set to level 3 
Using office base path: /usr/lib64/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener successfully started. (pid=31074)
Input file: directive_1640_56.odt
```

CPU usage of the LO process goes up to 100 %, and nothing further happens. It looks/feels like LO is stuck in some kind of infinite loop or similar, the whole process isn't usable anymore.

The file in question: [directive.zip](https://github.com/dagwieers/unoconv/files/1991417/directive.zip)
It's a generated file using [appy pod](http://appyframework.org/pod.html).

LibreOffice version is 5.4.6.2 40m0(Build:2)

**Comment by michi88** [comment]
I can confirm this as well, see my comments here: https://bugs.documentfoundation.org/show_bug.cgi?id=117625

**Comment by regebro** [comment]
Libreoffice bug, closing.
