### ISSUE TITLE
Cannot find a suitable office installation on your system.

### ISSUE THREAD

**Issue by wb-gj198118** [dagwieers/unoconv#452]
system : macOS High Sierra version: 10.13.4

**Comment by regebro** [comment]
I've noticed that when these issues arise, the solution is to run unoconv with the python executable that comes with the Libreoffice installation you want to use. Like so:

```
UNOPATH=/path/to/Libreoffice /path/to/Libreoffice/program/python /usr/bin/unoconv ....
```
Yes, that's fairly annoying, but only happens with multiple LibreOffice and/or Python installations.

Further discussion on #49
