### ISSUE TITLE
MacBook OS 10.13.3 Sierra installation failed

### ISSUE THREAD

**Issue by chaowu2009** [dagwieers/unoconv#453]
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
cwu:unoconv chaowu$ unoconv  --help
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

**Comment by regebro** [comment]
See #49
