### ISSUE TITLE
Missing urls when conversion from pdf to odp

### ISSUE THREAD

**Issue by Jurigag** [dagwieers/unoconv#459]
When converting pdf file to odp it loses hiperlinks for some reason. In pdf they are working correctly, but text is shorten so it's not fully presented as a text and then in odp it is missing for some reason. Also not sure why but when i open same pdf file in libreoffice there is no link too. Does libreoffice only recognize full links or what?

More info - im using wkhtmltopdf to generate pdf from html so i have just link like `<a href="url">shorten url without https and few less letters etc</a>` then when i open this pdf in program like Foxit Reader it works correctly but both in LibreOffice and when converting from odp to pdf it doesn't work, any idea what's going on?

**Comment by regebro** [comment]
This is a LibreOffice issue. Unoconv only uses it, and can't fix any issues with it.
