### ISSUE TITLE
Release a new version and update the one on hombrew

### ISSUE THREAD

**Issue by markn86** [dagwieers/unoconv#461]
Can you please release a new version and update the one used by Homebrew? It would be nice to have support for Libreoffice 5.x introduced in https://github.com/dagwieers/unoconv/commit/5719f58b327f384b13b20eef963590ff50702e9f.

**Comment by Eitz** [comment]
Guys, please?

**Comment by regebro** [comment]
We don't do anything with homebrew.

**Comment by p8** [comment]
I've created a tap for homebrew which works with master: https://github.com/p8/homebrew-unoconv
