### ISSUE TITLE
rotated output file

### ISSUE THREAD

**Issue by Adblu** [dagwieers/unoconv#462]
When im converting for example horizontal jpg to tiff file, the tiff file looks weird. Horizontal image is placed into veritical. 
Example:

[![image.png](https://s15.postimg.cc/qupgcvivv/image.png)](https://postimg.cc/image/s9r11ljyv/)

is there any way to fix it ?

**Comment by regebro** [comment]
No, that's per design. You imported the jpg into a Draw document, and then exported the document.

Unoconv is not an image converter, it's a document converter, simply speaking.
