### ISSUE TITLE
How to use it on RHEL?

### ISSUE THREAD

**Issue by chanbyeoldaddy** [dagwieers/unoconv#464]
Hi, all.
Would you guide me how to use on RHEL?

**Comment by bertalanimre** [comment]
Specify your question please. You want unoconv to run as a service so you can use with webapplications? Or you just wish to convert files in terminal? This question is not gonna get you far.

**Comment by ajayamuduli** [comment]
Hi,
I want to convert a ppt files to pdf in rhel.
could you please help on this.

Best Reagrds,
Ajaya
