### ISSUE TITLE
Does anyone else have an issue with columns/section breaks when converting from .docx to .pdf?

### ISSUE THREAD

**Issue by DavidAyliffe** [dagwieers/unoconv#477]
Any .docx documents with section breaks in ruin the format of the converted file.
I'm running unoconv on Mac with LibreOffice (of course)

**Comment by regebro** [comment]
Does it work if you export it to PDF with LibreOffice directly?
If so, can you make an example file, and also provide the command line you use to convert to PDF?

**Comment by DavidAyliffe** [comment]
[Test from Unoconv.pdf](https://github.com/dagwieers/unoconv/files/2620799/Test.from.Unoconv.pdf)
[test from LibreOffice 4372.pdf](https://github.com/dagwieers/unoconv/files/2620800/test.from.LibreOffice.4372.pdf)
[test from Word.pdf](https://github.com/dagwieers/unoconv/files/2620801/test.from.Word.pdf)
[test.docx](https://github.com/dagwieers/unoconv/files/2620802/test.docx)

The output from LibreOffice and UnoConv are consistent but it's annoying that LO is putting text directly after a section break on a new page.

This really screws up the formatting of a lot of our documents.
Is there any solution?

Maybe this has been fixed in the latest version of LO.  Any timeframe on when UnoConv will support this?

My command line is:
if ( system ( 'unoconv', '--preserve', '-f', 'pdf', $item->{filename} ) == 0 ) # success!   
{ ... }

**Comment by regebro** [comment]
I hope to get some time to spend on Unoconv during December, but I can't promise anything. But in any case this is a LibreOffice problem, not a Unoconv one. I'll keep it open until we can officially support Libreoffice 6.

**Comment by DavidAyliffe** [comment]
If you can find some time, that'd be great.  This section break issue a big
problem for us and benefiting from the other features and fixes in LO6 is
also desirable.

Thanks again.

**Comment by DavidAyliffe** [comment]
To add some context to your work.

We are a university teaching English to students for whom English is not
their first language.  We create a lot of our materials ourselves in docx
format and store them centrally on a Learning Management System (like
Facebook but for learning).

Periodically, we pull all of our material down and use unoconv to convert
these docx files first to pdf and then into one big pdf which we make
available to our students to print off and bring to class.

We currently have lots of issues with section breaks and documents not
looking the same when we create them in Word as they do in LO.  We
understand that this is LO misbehaving and no unoconv..
But, the sooner unoconv can support LO 6.X, the sooner we can get back to
focusing on making materials better instead of wasting hours removing
section breaks.

Thanks again for your work on this project.

**Comment by regebro** [comment]
Unoconv seems to work with Libreoffice 6 as far as my testing goes.
