### ISSUE TITLE
centos 7 :unoconv convert docx to pdf , pdf has more pages than docx! anyone has come up with this ?

### ISSUE THREAD

**Issue by guanshan99** [dagwieers/unoconv#480]

**Comment by DavidAyliffe** [comment]
Yes. Take a look at ticket 477.
A docx with section breaks on Mac using LO 4.3.7.2 will bleed over onto an
additional page.

**Comment by regebro** [comment]
This is an issue with LibreOffice.

**Comment by yangweijie** [comment]
i meet with old libreoffice5.3  then libreoffice6.2 fixed this. But my server centos7 install 5.3
