### ISSUE TITLE
verbose output for listener

### ISSUE THREAD

**Issue by tobwen** [dagwieers/unoconv#481]
Could you please add some kind of logging or verbose output to the listener? 

`unoconv -vvv --listener` currently only returns this without any details when it got triggered:
```
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
Start listener on 127.0.0.1:2002
```

**Comment by regebro** [comment]
I don't know what output you expect. The output from unoconv will come from the unoconv command. Any output the soffice listener does will come at the listener. I don't think that is even possible to change.

**Comment by tobwen** [comment]
Things that you can expect from verbosity level 3: Statistical information, like processing time, which IP has connected etc.

_It is not very polite to close a question directly, although the opposite side is not even given the opportunity to comment or answer the open questions. Normally, one asks for feedback (there's normally a tag for it)._

**Comment by regebro** [comment]
That logging is done by Libreoffice, we can't do anything about that.
