### ISSUE TITLE
The latest release 0.8.2 is not available via apt-get

### ISSUE THREAD

**Issue by headz68** [dagwieers/unoconv#482]
I'm trying to install unoconv inside a Debian stretch docker container using apt-get but it installs version 0.7. I've updated the registry and here's my output from `apt-cache policy unoconv`
```
unoconv:
  Installed: 0.7-1.1
  Candidate: 0.7-1.1
  Version table:
 *** 0.7-1.1 500
        500 http://httpredir.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```
I need the latest version so I can use the `-P` option for converting spreadsheets into PDFs in landscape. Can someone publish the latest version or am I missing something?

**Comment by regebro** [comment]
I don't know who makes the Debian packages.

You should be able to install the latest version with pip install unoconv, though, try that.
