### ISSUE TITLE
How do I use graphics export options?

### ISSUE THREAD

**Issue by serverdevil** [dagwieers/unoconv#487]
I'm converting a pdf to png (need the first page only) using the following command

` unoconv -d graphics -o output/doc.png -f png -v doc.pdf`

I need to restrict the image size to generate a thumbnail, for which I'd expect the export option to work as follows but it doesn't effect any change

` unoconv -d graphics -o output/doc.png -e Width=25 -f png -v doc.pdf`

Also, how do I combine multiple export filter options?

**Comment by regebro** [comment]
You can have multiple `-e` parameters, like `-e Width=25 -e Height=100`, but you are right, `Width` and  `Height` does not work for me either. I don't know if this is a Libreoffice bug or if they are actually called something else.

In any case, Libreoffice is not the best tool for this. I think I used ImageMagick last time I needed to make a PDF thumbnail. I think Ghostscript might work as well.

**Comment by serverdevil** [comment]
Thanks @regebro. Imagemagick is exactly what I ended up using.

**Comment by regebro** [comment]
OK, and it turns out that height and width work, but you have to specify both.
