### ISSUE TITLE
Creation of executable memory area failed: Permission denied

### ISSUE THREAD

**Issue by Yuseinov** [dagwieers/unoconv#85]
In my `ubuntu 10.04 64bit Server` i can't start `unoconv` from `apache/php` - (`www-data user`).
When i start whit `admin`(`root` user) converting work correct. But when start `unoconv` like `www-data` user program is crashing with error:
```
creation of executable memory area failed: Permission denied
unoconv: UnoException during conversion:
The provided document cannot be converted to the desired format.
Leaking python objects bridged to UNO for reason pyuno runtime is not initialized, (the pyuno.bootstrap needs to be called before using any uno classes)
``` 
If i start `unoconv` in `sudo` mode whit `www-data` user again still does not work on `Server`.
In my local machine i don' t have a problem. I can start `unoconv` from `apache`, but my server I can't.

I removed `SELinux`, i have installed `xvfb` and i have permissions to write and read in the folder and files.

**Comment by dagwieers** [comment]
So we are tracking all related issues in ticket #87. I proposed a few solutions, feedback is welcome.
As a result I am closing this issue. Thanks for all the feedback !

**Comment by t003** [comment]
Hello

i keep getting this error if i want to convert a .docx to a .pdf file

Leaking python objects bridged to UNO for reason pyuno runtime is not initialized, (the pyuno.bootstrap needs to be called before using any uno classes)

**Comment by massicos** [comment]
Hi,

we also got this problem (Leaking python). Our config is :

* Rehdat 6
* libreOffice 5.2 from RPM
* unoconv 0.7 as a deamon with a user a home directory (we are working to make it work with apache user)
  * with the path /opt/libreoffice5.2/program/python in the beginning of the script

We don't have it a lot of time and when we got it the PDF is generated with success (about 2-3 times for 100 conversions).
