### ISSUE TITLE
Errors message on converting from odt to pdf (ErrCode 19468)

### ISSUE THREAD

**Issue by Sworddragon** [dagwieers/unoconv#90]
I'm using unoconv 0.6 and LibreOffice 3.6.1 RC2. On converting a document to a pdf file I'm getting this error (just ignore the Fontconfig warning):

```
sworddragon@ubuntu:~$ /home/sworddragon/data/unoconv-0.6/unoconv /tmp/test.odt /tmp/test.pdf
Fontconfig warning: "/usr/lib/libreoffice/share/fonts/truetype/fc_local.conf", line 13: Having multiple <family> in <alias> isn't supported and may not works as expected
unoconv: UnoException during export phase:
Unable to store document to file:///tmp/test.pdf (ErrCode 19468)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"writer_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x2cc6b98{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```

**Comment by dagwieers** [comment]
@thomaspurchas Thanks for the clear explanation. Do you have a suggestion to how the manual could make this more clear ? There is an `-o` and `--output` option, to influence the output location.

**Comment by dagwieers** [comment]
I'd like to release v0.7 next week.
If we can improve the documentation so people are less confused by how unoconv is to be used, let me know ASAP.

**Comment by dagwieers** [comment]
As a reference, ErrCode 19468 has a very specific meaning:

Binary: 010:01100:00001100
 - Area: 2 (ERRCODE_AREA_SFX)
 - Class: 12 (ERRCODE_CLASS_WRITE)
 - Code: 12 (ERRCODE_IO_NOTSUPPORTED)

And this boils down to: **ERRCODE_SFX_DOCUMENTREADONLY**

**Comment by regebro** [comment]
There seems to be no issue remaining here.
