### ISSUE TITLE
Unsupported URL on 64bit Ubuntu 12.04

### ISSUE THREAD

**Issue by nielssteenkrogh** [dagwieers/unoconv#95]
Did like this:
1. apt-get install unoconv
2. apt-get install libreoffice
3. replaced the unoconv with the lastes from github

Before step 2 the unoconv failed with "url not supported" error for any document type
I was bit confused by having a libreoffice --version also after step1
But looks like the filters were not in place by then - anyway - now works perfect for docx conversions

**Comment by dagwieers** [comment]
Is this issue still pertinent ?

If so, feel free to reopen this issue and provide us with the details from the [Troubleshooting instructions](https://github.com/dagwieers/unoconv#troubleshooting-instructions) using the latest unoconv from the master branch and a recent version of LibreOffice.

Thanks for the feedback !
